package com.gp.cong.logisoft.domain;

import java.util.Date;

/**
 * AbstractUniverseFlatRate generated by MyEclipse - Hibernate Tools
 */
public class UniverseFlatRateHistory implements java.io.Serializable {

    // Fields    
    private Integer id;
    private Integer universeId;
    private Double amount;
    private GenericCode unitType;
    private Date effectiveDate;
    private Date changedDate;
    private String whoChanged;

    // Constructors
    /**
     * default constructor
     */
    public UniverseFlatRateHistory() {
    }

    /**
     * minimal constructor
     */
    public UniverseFlatRateHistory(String whoChanged) {
        this.whoChanged = whoChanged;
    }

    /**
     * full constructor
     */
    public UniverseFlatRateHistory(Integer universeId, Double amount, Integer unitType, Date effectiveDate, Date changedDate, String whoChanged) {
        this.universeId = universeId;
        this.amount = amount;
        //this.unitType = unitType;
        this.effectiveDate = effectiveDate;
        this.changedDate = changedDate;
        this.whoChanged = whoChanged;
    }

    // Property accessors
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUniverseId() {
        return this.universeId;
    }

    public void setUniverseId(Integer universeId) {
        this.universeId = universeId;
    }

    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public GenericCode getUnitType() {
        return unitType;
    }

    public void setUnitType(GenericCode unitType) {
        this.unitType = unitType;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public Date getChangedDate() {
        return this.changedDate;
    }

    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    public String getWhoChanged() {
        return this.whoChanged;
    }

    public void setWhoChanged(String whoChanged) {
        this.whoChanged = whoChanged;
    }
}