/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gp.cong.logisoft.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gp.cong.logisoft.domain.Customer;
import com.gp.cong.logisoft.domain.CustomerAccounting;
import com.gp.cong.logisoft.domain.CustomerContact;
import com.gp.cong.logisoft.struts.form.ContactPopupForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-06-2008
 * 
 * XDoclet definition:
 * @struts.action path="/contactPopup" name="contactPopupForm" input="/jsps/Tradingpartnermaintainance/contactPopup.jsp" scope="request" validate="true"
 */
public class ContactPopupAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ContactPopupForm contactPopupForm = (ContactPopupForm) form;// TODO Auto-generated method stub
		HttpSession session = ((HttpServletRequest)request).getSession();
		
		String bvalue="";
		String path="";
		if(session.getAttribute("button")!=null)
		{
			bvalue= (String)session.getAttribute("button");
		}
		
		CustomerContact customerCont=new CustomerContact();//-------------CONFIG OBJECT---------
		CustomerAccounting accntList= new CustomerAccounting();//-------Accounting page object-----
		List conList=new ArrayList();
		
		if(request.getParameter("ind")!=null)
		{
			int ind=Integer.parseInt(request.getParameter("ind"));
			
			if(bvalue.equals("cont")||bvalue.equals("editcont")||bvalue.equals("mcont")||bvalue.equals("meditcont"))
			{	
				if(session.getAttribute("addConfig")!=null)
				{
					conList=(List)session.getAttribute("addConfig");
				}
				
			}
			
			customerCont=(CustomerContact)conList.get(ind);
			
			if(bvalue.equals("cont")||bvalue.equals("editcont"))//---------FOR ACCOUNTING PAGE-------
			{
				if(session.getAttribute("accounting")!=null)
				{
					accntList=(CustomerAccounting)session.getAttribute("accounting");
					
				}
				else
				{
					accntList= new CustomerAccounting();
				}
		    }
			
			if(bvalue.equals("mcont")||bvalue.equals("meditcont"))//---------FOR MASTER ACCOUNTING PAGE-----
			{
				
				if(session.getAttribute("masteraccounting")!=null)
				{
					accntList=(CustomerAccounting)session.getAttribute("masteraccounting");
				}
				else
				{
					accntList= new CustomerAccounting();
				}
				
			}
			if(bvalue.equals("cont")||bvalue.equals("editcont")||bvalue.equals("mcont")||bvalue.equals("meditcont"))
			{
				accntList.setContact(customerCont.getFirstName()+customerCont.getLastName());
				accntList.setArFax(customerCont.getFax());
				accntList.setArPhone(customerCont.getPhone());
				accntList.setAcctRecEmail(customerCont.getEmail());
			}
			
			if(bvalue.equals("cont") || bvalue.equals("editcont"))
			{
				session.setAttribute("accounting", accntList);
			}
			if(bvalue.equals("mcont") || bvalue.equals("meditcont"))
			{
				session.setAttribute("masteraccounting", accntList);
			}
			//session.setAttribute("CPlist", accntList);
			request.setAttribute("close","close" );
			
			if(bvalue.equals("cont"))
			{
				path="/jsps/Tradingpartnermaintainance/Accounting.jsp";
			}
			if(bvalue.equals("editcont"))
			{
				path="/jsps/Tradingpartnermaintainance/EditAccounting.jsp";
			}
			if(bvalue.equals("mcont"))
			{
				path="/jsps/Tradingpartnermaintainance/MasterAccounting.jsp";
			}
			if(bvalue.equals("meditcont"))
			{
				path="/jsps/Tradingpartnermaintainance/masterEditAccounting.jsp";
			}
			request.setAttribute("path1", path);
		}
		
		
		return mapping.findForward("tocont");
	}
}