/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gp.cong.logisoft.struts.action;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gp.cong.logisoft.domain.ClaimDetails;
import com.gp.cong.logisoft.domain.CustomerContact;
import com.gp.cong.logisoft.struts.form.EditClaimDetailsForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-14-2008
 * 
 * XDoclet definition:
 * @struts.action path="/editClaimDetails" name="editClaimDetailsForm" input="/jsps/datareference/EditClaimDetails.jsp" scope="request" validate="true"
 */
public class EditClaimDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws Exception {
		EditClaimDetailsForm editClaimDetailsForm = (EditClaimDetailsForm) form;// TODO Auto-generated method stub
		HttpSession session = ((HttpServletRequest)request).getSession();
		String buttonValue=editClaimDetailsForm.getButtonValue();
		String masterawb1=editClaimDetailsForm.getMasterAwb2();
		String masterawb2=editClaimDetailsForm.getMasterAwb3();
		String masterawb3=editClaimDetailsForm.getMasterAwb1();
		String portNumber=editClaimDetailsForm.getPortNo();
		SimpleDateFormat sdf=new SimpleDateFormat("MM/dd/yyyy");
		String flightDate=editClaimDetailsForm.getTxtcal();
		String hazardous=editClaimDetailsForm.getHazardous();
		String claimed=editClaimDetailsForm.getClaimed();
		String masterawb="";
		masterawb=masterawb3+"-"+masterawb1+"-"+masterawb2;
		ClaimDetails claim=null;
		List claimdetailslist=new ArrayList();
		if(buttonValue.equals("save"))
		{
			if(session.getAttribute("cld")!=null)
			{
			claim=(ClaimDetails)session.getAttribute("cld");
			}
			claim.setMasterAwbNo(masterawb);
			claim.setPortNumber(portNumber);
			if(flightDate!=null && flightDate!="")
			{
				java.util.Date javaDate=null;
					javaDate=sdf.parse(flightDate);
				claim.setFlightDate(javaDate);
			}
			if(hazardous!=null &&  hazardous.equalsIgnoreCase("on"))
			{
				claim.setHazardous("Y");
			}
			else if(hazardous==null || hazardous.equalsIgnoreCase("off"))
			{
				claim.setHazardous("N");
			}
			if(claimed!=null && claimed.equalsIgnoreCase("on"))
			{
				claim.setClaim("claimed");
				Date date1=new Date(System.currentTimeMillis()); 
				//SimpleDateFormat sd=new SimpleDateFormat("MM-dd-yyyy hh:mm:ss");
				//String userDate=String.valueOf(sd.format(date1));
				claim.setClaimDate(date1);
			}
			else if(claimed!=null && claimed.equalsIgnoreCase("off"))
			{
				claim.setClaim("unclaimed");
			}
			if(session.getAttribute("claimdetailslist")!=null)
			{
			claimdetailslist=(List)session.getAttribute("claimdetailslist");
			for(int i=0;i<claimdetailslist.size();i++)
			{
				ClaimDetails claim1=(ClaimDetails)claimdetailslist.get(i);
				if(claim1.getIndex()==claim.getIndex())
				{
					claim.setIndex(claim1.getIndex());
					claimdetailslist.remove(claim1);
				}
			}
			claimdetailslist.add(claim);
			}
			request.setAttribute("editclaim", "edit");
		}
		else if(buttonValue.equals("cancel"))
		{
			request.setAttribute("editclaim", "edit");
		}
		return mapping.findForward("editclaim");
	}
}