/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gp.cong.logisoft.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gp.cong.logisoft.struts.form.SearchCityForm;
import com.gp.cong.logisoft.domain.AirPortConfiguration;
import com.gp.cong.logisoft.domain.Customer;
import com.gp.cong.logisoft.domain.CustomerAccounting;
import com.gp.cong.logisoft.domain.Ports;
import com.gp.cong.logisoft.domain.RefTerminal;
import com.gp.cong.logisoft.domain.UnLocation;
import com.gp.cong.logisoft.domain.UnitLocation;
import com.gp.cong.logisoft.domain.User;
import com.gp.cong.logisoft.domain.Warehouse;
import com.gp.cong.logisoft.hibernate.dao.*;

/** 
 * MyEclipse Struts
 * Creation date: 02-07-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SearchcityAction extends Action {
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response) throws Exception {
        HttpSession session = ((HttpServletRequest) request).getSession();
        SearchCityForm searchform = (SearchCityForm) form;
        String buttonValue = searchform.getButtonValue();
        String search = "";

        UnLocationDAO unLocationDAO = new UnLocationDAO();
        String path1 = "";
        if (request.getParameter("index") != null) {

            int ind = Integer.parseInt(request.getParameter("index"));
            List cityList = (List) session.getAttribute("cityDetails");
            UnLocation citySelBean = (UnLocation) cityList.get(ind);

            if (session.getAttribute("search1") != null) {
                search = (String) session.getAttribute("search1");
            }
            if (search.equals("searchterminalcity") || search.equals("editterminalcity")) {
                RefTerminal terminal = null;
                if (session.getAttribute("terminal") == null) {
                    terminal = new RefTerminal();
                } else {
                    terminal = (RefTerminal) session.getAttribute("terminal");
                }


                terminal.setCountry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    terminal.setState(citySelBean.getStateId().getCode());
                }
                terminal.setUnLocation(citySelBean);
                terminal.setCity1(citySelBean.getUnLocationName());
                if (search.equals("searchterminalcity")) {
                    path1 = "jsps/datareference/NewTerminal.jsp";
                } else if (search.equals("editterminalcity")) {
                    path1 = "jsps/datareference/EditTerminal.jsp";
                }
            } else if (search.equals("searchportcity") || search.equals("editportcity")) {
                Ports portobj = null;
                if (session.getAttribute("portobj") == null) {
                    portobj = new Ports();
                } else {
                    portobj = (Ports) session.getAttribute("portobj");
                }
                portobj.setPortname(citySelBean.getUnLocationName());
                portobj.setUncitycode(citySelBean);

                portobj.setCountryName(citySelBean.getCountryId().getCodedesc());
                session.setAttribute("portobj", portobj);
                if (search.equals("searchportcity")) {
                    path1 = "jsps/datareference/portDetails.jsp";
                } else if (search.equals("editportcity")) {
                    path1 = "jsps/datareference/editPortDetails.jsp";
                }
            } else if (search.equals("searchcustomercity") || search.equals("mastereditcustomercity")) {
                Customer customer = null;
                if (session.getAttribute("customer") == null) {
                    customer = new Customer();
                } else {
                    customer = (Customer) session.getAttribute("customer");
                }
                customer.setCity1(citySelBean);
                customer.setCity2(citySelBean.getUnLocationName());
                customer.setCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    customer.setState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("customer", customer);

                if (search.equals("searchcustomercity")) {
                    path1 = "jsps/Tradingpartnermaintainance/addCustomer.jsp";
                } else if (search.equals("mastereditcustomercity")) {
                    path1 = "jsps/Tradingpartnermaintainance/masterEditCustomer.jsp";
                }
            } else if (search.equals("editaddress")) {
                Customer customer = null;
                if (session.getAttribute("adressCust") == null) {
                    customer = new Customer();
                } else {
                    customer = (Customer) session.getAttribute("adressCust");
                }
                customer.setCity1(citySelBean);
                customer.setCity2(citySelBean.getUnLocationName());
                customer.setCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    customer.setState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("adressCust", customer);
                if (search.equals("editaddress")) {
                    path1 = "jsps/Tradingpartnermaintainance/EditAddress.jsp";
                }

            } else if (search.equals("masteraccountingcity") || search.equals("mastereditaccountingcity")) {
                CustomerAccounting accounting = null;
                if (session.getAttribute("masteraccounting") == null) {
                    accounting = new CustomerAccounting();
                } else {
                    accounting = (CustomerAccounting) session.getAttribute("masteraccounting");
                }
                accounting.setCity1(citySelBean);
                accounting.setCity2(citySelBean.getUnLocationName());
                accounting.setCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    accounting.setState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("masteraccounting", accounting);
                if (search.equals("masteraccountingcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/MasterAccounting.jsp";
                } else if (search.equals("mastereditaccountingcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/masterEditAccounting.jsp";
                }
            } else if (search.equals("masteraccountingffcity") || search.equals("mastereditaccountingffcity")) {
                CustomerAccounting accounting = null;
                if (session.getAttribute("masteraccounting") == null) {
                    accounting = new CustomerAccounting();
                } else {
                    accounting = (CustomerAccounting) session.getAttribute("masteraccounting");
                }
                accounting.setPayCity1(citySelBean);
                accounting.setPaycity2(citySelBean.getUnLocationName());
                accounting.setPayCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    accounting.setPayState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("masteraccounting", accounting);
                if (search.equals("masteraccountingffcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/MasterAccounting.jsp";
                } else if (search.equals("mastereditaccountingffcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/masterEditAccounting.jsp";
                }
            } else if (search.equals("searchwarehousecity") || search.equals("editwarehousecity")) {
                Warehouse warehouse = null;
                if (session.getAttribute("warehouse") == null) {
                    warehouse = new Warehouse();
                } else {
                    warehouse = (Warehouse) session.getAttribute("warehouse");

                }

                warehouse.setCityCode(citySelBean);
                warehouse.setCity(citySelBean.getUnLocationName());
                if (citySelBean.getStateId() != null) {
                    warehouse.setState(citySelBean.getStateId().getCode());
                }
                warehouse.setCountryCode(citySelBean.getCountryId());

                session.setAttribute("warehouse", warehouse);
                if (search.equals("searchwarehousecity")) {
                    path1 = "jsps/datareference/addWarehouse.jsp";
                } else if (search.equals("editwarehousecity")) {
                    path1 = "jsps/datareference/editWarehouse.jsp";
                }
            } else if (search.equals("searchacwarehousecity") || search.equals("editacwarehousecity")) {
                Warehouse warehouse = null;
                if (session.getAttribute("warehouse") == null) {
                    warehouse = new Warehouse();
                } else {
                    warehouse = (Warehouse) session.getAttribute("warehouse");
                }

                warehouse.setAcCity(citySelBean);
                warehouse.setAirCity(citySelBean.getUnLocationName());
                if (citySelBean.getStateId() != null) {
                    warehouse.setAcState(citySelBean.getStateId().getCode());
                }
                warehouse.setAcCountryCode(citySelBean.getCountryId());
                session.setAttribute("warehouse", warehouse);
                if (search.equals("searchacwarehousecity")) {
                    path1 = "jsps/datareference/addWarehouse.jsp";
                } else if (search.equals("editacwarehousecity")) {
                    path1 = "jsps/datareference/editWarehouse.jsp";
                }
            } else if (search.equals("searchusercity") || search.equals("editusercity")) {
                User user = null;
                if (session.getAttribute("user") == null) {
                    user = new User();
                } else {
                    user = (User) session.getAttribute("user");
                }
                user.setUnLocation(citySelBean);
                user.setGenericCode(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    user.setState(citySelBean.getStateId().getCode());
                }
                user.setCity(citySelBean.getUnLocationName());
                session.setAttribute("user", user);
                if (search.equals("searchusercity")) {
                    path1 = "jsps/admin/NewUser.jsp";
                } else if (search.equals("editusercity")) {
                    path1 = "jsps/admin/EditUser.jsp";
                }
            } else if (search.equals("searchcustomercity") || search.equals("editcustomercity")) {
                Customer customer = null;
                if (session.getAttribute("customer") == null) {
                    customer = new Customer();
                } else {
                    customer = (Customer) session.getAttribute("customer");
                }
                customer.setCity1(citySelBean);
                customer.setCity2(citySelBean.getUnLocationName());
                customer.setCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    customer.setState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("customer", customer);
                if (search.equals("searchcustomercity")) {
                    path1 = "jsps/Tradingpartnermaintainance/Customer.jsp";
                } else if (search.equals("editcustomercity")) {
                    path1 = "jsps/Tradingpartnermaintainance/EditCustomer.jsp";
                }
            } else if (search.equals("accountingcity") || search.equals("editaccountingcity")) {
                CustomerAccounting accounting = null;
                if (session.getAttribute("accounting") == null) {
                    accounting = new CustomerAccounting();
                } else {
                    accounting = (CustomerAccounting) session.getAttribute("accounting");
                }
                accounting.setCity1(citySelBean);
                accounting.setCity2(citySelBean.getUnLocationName());
                accounting.setCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    accounting.setState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("accounting", accounting);
                if (search.equals("accountingcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/Accounting.jsp";
                } else if (search.equals("editaccountingcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/EditAccounting.jsp";
                }
            } else if (search.equals("masteraccountingcity") || search.equals("editaccountingcity")) {
                CustomerAccounting accounting = null;
                if (session.getAttribute("accounting") == null) {
                    accounting = new CustomerAccounting();
                } else {
                    accounting = (CustomerAccounting) session.getAttribute("accounting");
                }
                accounting.setCity1(citySelBean);
                accounting.setCity2(citySelBean.getUnLocationName());
                accounting.setCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    accounting.setState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("accounting", accounting);
                if (search.equals("masteraccountingcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/MasterAccounting.jsp";
                } else if (search.equals("editaccountingcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/EditAccounting.jsp";
                }
            } else if (search.equals("accountingffcity") || search.equals("editaccountingffcity")) {
                CustomerAccounting accounting = null;
                if (session.getAttribute("accounting") == null) {
                    accounting = new CustomerAccounting();
                } else {
                    accounting = (CustomerAccounting) session.getAttribute("accounting");
                }
                accounting.setPayCity1(citySelBean);
                accounting.setPaycity2(citySelBean.getUnLocationName());
                accounting.setPayCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    accounting.setPayState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("accounting", accounting);
                if (search.equals("accountingffcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/Accounting.jsp";
                } else if (search.equals("editaccountingffcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/EditAccounting.jsp";
                }
            } else if (search.equals("masteraccountingffcity") || search.equals("editaccountingffcity")) {
                CustomerAccounting accounting = null;
                if (session.getAttribute("accounting") == null) {
                    accounting = new CustomerAccounting();
                } else {
                    accounting = (CustomerAccounting) session.getAttribute("accounting");
                }
                accounting.setPayCity1(citySelBean);
                accounting.setPaycity2(citySelBean.getUnLocationName());
                accounting.setPayCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    accounting.setPayState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("accounting", accounting);
                if (search.equals("masteraccountingffcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/MasterAccounting.jsp";
                } else if (search.equals("editaccountingffcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/EditAccounting.jsp";
                }
            } else if (search.equals("mastersearchcustomercity") || search.equals("editaccountingffcity")) {
                Customer customer = null;
                if (session.getAttribute("customer") == null) {
                    customer = new Customer();
                } else {
                    customer = (Customer) session.getAttribute("customer");
                }
                customer.setCity1(citySelBean);
                customer.setCity2(citySelBean.getUnLocationName());
                customer.setCuntry(citySelBean.getCountryId());
                if (citySelBean.getStateId() != null) {
                    customer.setState(citySelBean.getStateId().getCode());
                }
                session.setAttribute("customer", customer);
                if (search.equals("mastersearchcustomercity")) {
                    path1 = "jsps/Tradingpartnermaintainance/MasterCustomer.jsp";
                } else if (search.equals("editaccountingffcity")) {
                    path1 = "jsps/Tradingpartnermaintainance/EditAccounting.jsp";
                }
            } //for container unit location
            else if (search.equals("currentlocation")) {
                UnitLocation unitLocation = null;
                if (session.getAttribute("currentlocation") == null) {
                    unitLocation = new UnitLocation();
                } else {
                    unitLocation = (UnitLocation) session.getAttribute("currentlocation");
                }
                unitLocation.setCurrentLocation(citySelBean.getUnLocationName());
                session.setAttribute("currentlocation", unitLocation);
                if (search.equals("currentlocation")) {
                    path1 = "jsps/Containermanagement/AddLocPopup.jsp";
                }

            } //
            else if (search.equals("currentlocation1")) {
                UnitLocation unitLocation = null;
                if (session.getAttribute("currentlocation") == null) {
                    unitLocation = new UnitLocation();
                } else {
                    unitLocation = (UnitLocation) session.getAttribute("currentlocation");
                }
                unitLocation.setCurrentLocation(citySelBean.getUnLocationName());
                session.setAttribute("currentlocation", unitLocation);
                if (search.equals("currentlocation1")) {
                    path1 = "jsps/Containermanagement/UpdateLocPopup.jsp";
                }
            } else if (search.equals("editairportcity") || search.equals("newairportcity")) {
                AirPortConfiguration airPortObj = null;
                if (search.equals("editairportcity")) {
                    if (session.getAttribute("airPortObjConfigConfiguration") != null) {
                        airPortObj = (AirPortConfiguration) session.getAttribute("airPortObjConfigConfiguration");
                    } else {
                        airPortObj = new AirPortConfiguration();
                    }
                    airPortObj.setAirPortCityId(citySelBean.getUnLocationName());

                    path1 = "jsps/datareference/editAirportConfig.jsp";
                } else if (search.equals("newairportcity")) {
                    if (session.getAttribute("airPortObj") != null) {
                        airPortObj = (AirPortConfiguration) session.getAttribute("airPortObj");
                    } else {
                        airPortObj = new AirPortConfiguration();
                    }

                    airPortObj.setAirPortCityId(citySelBean.getUnLocationName());
                    path1 = "jsps/datareference/airPortConfiguration.jsp";
                }
            }
            request.setAttribute("path1", path1);
            request.setAttribute("buttonValue", "completed");
            List lList = (List) session.getAttribute("cityDetails");
            session.removeAttribute("cityDetails");

            if (lList != null && lList.size() > 0) {
                lList.clear();
            }
        } else {
            if (buttonValue != null && buttonValue.equals("search")) {
                List city = unLocationDAO.findbyCity(request.getParameter("city"));
                List lList = (List) session.getAttribute("cityDetails");
                if (session.getAttribute("cityDetails") != null) {
                    session.removeAttribute("cityDetails");
                }
                if (lList != null && lList.size() > 0) {
                    lList.clear();
                }

                session.setAttribute("cityDetails", city);

            }
        }

        return mapping.findForward("searchpopup");
    }
}