/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gp.cong.logisoft.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gp.cong.logisoft.hibernate.dao.RefTerminalDAO;
import com.gp.cong.logisoft.struts.form.SearchTerminalNumberForm;
import com.gp.cong.logisoft.domain.RefTerminalTemp;

/** 
 * MyEclipse Struts
 * Creation date: 08-01-2008
 * 
 * XDoclet definition:
 * @struts.action path="/searchTerminalNumber" name="searchTerminalNumberForm" input="/jsps/datareference/searchTerminalNumber.jsp" scope="request" validate="true"
 * @struts.action-forward name="searchTerminalNumber" path="/searchTerminalNumber"
 */
public class SearchTerminalNumberAction extends Action {

    /**
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response) throws Exception {
        SearchTerminalNumberForm searchTerminalNumberForm = (SearchTerminalNumberForm) form;// TODO Auto-generated method stub
        HttpSession session = request.getSession();
        String termNo = searchTerminalNumberForm.getTermNo();
        String termLoc = searchTerminalNumberForm.getTermName();
        String buttonValue = searchTerminalNumberForm.getButtonValue();
        String termType = "";
        String city = "";
        String index = searchTerminalNumberForm.getIndex();
        RefTerminalDAO terminalDAO = new RefTerminalDAO();

        RefTerminalTemp refTerminalobj = new RefTerminalTemp();
        if (request.getParameter("index") != null && request.getParameter("index") != "" || (index != null && !index.equals(""))) {

            int ind = Integer.parseInt(request.getParameter("index"));
            if (index != null) {
                ind = Integer.parseInt(index);
            }
            List termlist = (List) session.getAttribute("terminal");
            refTerminalobj = (RefTerminalTemp) termlist.get(ind);
            session.setAttribute("refTerminalobj", refTerminalobj);
            request.setAttribute("checked", "checked");

        } else {
            List terminal = terminalDAO.findForManagement(termNo, termLoc, termType, city);
            session.setAttribute("terminal", terminal);

            if (((List) session.getAttribute("terminal")).size() == 0) {
                session.setAttribute("Notfound", termNo);

            }
        }
        return mapping.findForward("searchTerminalNumber");
    }
}