/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gp.cong.logisoft.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gp.cong.logisoft.domain.AirPortConfiguration;
import com.gp.cong.logisoft.domain.FCLPortConfiguration;
import com.gp.cong.logisoft.domain.ImportPortConfiguration;
import com.gp.cong.logisoft.domain.LCLPortConfiguration;
import com.gp.cong.logisoft.domain.Ports;
import com.gp.cong.logisoft.domain.User;
import com.gp.cong.logisoft.domain.Warehouse;
import com.gp.cong.logisoft.hibernate.dao.UserDAO;
import com.gp.cong.logisoft.struts.form.UserPopUpForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2008
 * 
 * XDoclet definition:
 * @struts.action path="/userPopUp" name="userPopUpForm" input="/jsps/datareference/UserPopUp.jsp" scope="request" validate="true"
 */
public class UserPopUpAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		UserPopUpForm userPopUpForm = (UserPopUpForm) form;// TODO Auto-generated method stub
		HttpSession session = ((HttpServletRequest)request).getSession();
		String buttonValue=userPopUpForm.getButtonValue();
		String loginName=userPopUpForm.getLoginName();
		String lastName=userPopUpForm.getLastName();
		UserDAO userDAO=new UserDAO();
		String search="";
		String path1="";
		if(request.getParameter("index")!=null)
		{
//			User user1=new User();
//			int ind = Integer.parseInt(request.getParameter("index"));
//			List userList1=(List)session.getAttribute("userList");
//			if(session.getAttribute("search1")!=null)
//	 		{
//	 		search=(String)session.getAttribute("search1");
//	 		}
//			if(search.equals("lcl"))
//			{
//				LCLPortConfiguration lclPortobj=null;
//	 			if(session.getAttribute("lclPortobj")==null)
//	 			{
//	 				lclPortobj=new LCLPortConfiguration();
//	 			}
//	 			else
//	 			{
//	 				lclPortobj=(LCLPortConfiguration)session.getAttribute("lclPortobj");
//	 			}
//
//	 				path1="jsps/datareference/lclPortsConfig.jsp";
//
//
//	 			user1=(User)userList1.get(ind);
//	 			lclPortobj.setLineManager(user1);
//				session.setAttribute("lclPortobj", lclPortobj);
//			}
//			if(search.equals("editlcl"))
//			{
//				LCLPortConfiguration lclPortobj=null;
//	 			if(session.getAttribute("lclPortConfigurationObj")==null)
//	 			{
//	 				lclPortobj=new LCLPortConfiguration();
//	 			}
//	 			else
//	 			{
//	 				lclPortobj=(LCLPortConfiguration)session.getAttribute("lclPortConfigurationObj");
//	 			}
//
//	 				path1="jsps/datareference/editLclPortsConfig.jsp";
//
//
//	 			user1=(User)userList1.get(ind);
//	 			lclPortobj.setLineManager(user1);
//				session.setAttribute("lclPortConfigurationObj", lclPortobj);
//			}
//			else if(search.equals("fcl"))
//			{
//				FCLPortConfiguration fclPortobj=null;
//	 			if(session.getAttribute("fclPortobj")==null)
//	 			{
//	 				fclPortobj=new FCLPortConfiguration();
//	 			}
//	 			else
//	 			{
//	 				fclPortobj=(FCLPortConfiguration)session.getAttribute("fclPortobj");
//	 			}
//
//	 				path1="jsps/datareference/fclPortsConfiguration.jsp";
//
//	 			user1=(User)userList1.get(ind);
//	 			fclPortobj.setLineManager(user1);
//				session.setAttribute("fclPortobj", fclPortobj);
//			}
//			else if(search.equals("editfcl"))
//			{
//				FCLPortConfiguration fclPortobj=null;
//	 			if(session.getAttribute("fclPortObjConfiguration")==null)
//	 			{
//	 				fclPortobj=new FCLPortConfiguration();
//	 			}
//	 			else
//	 			{
//	 				fclPortobj=(FCLPortConfiguration)session.getAttribute("fclPortObjConfiguration");
//	 			}
//
//	 				path1="jsps/datareference/editFclPortsConfig.jsp";
//
//	 			user1=(User)userList1.get(ind);
//	 			fclPortobj.setLineManager(user1);
//				session.setAttribute("fclPortObjConfiguration", fclPortobj);
//			}
//			else if(search.equals("air"))
//			{
//				AirPortConfiguration airPortObj=null;
//	 			if(session.getAttribute("airPortObj")==null)
//	 			{
//	 				airPortObj=new AirPortConfiguration();
//	 			}
//	 			else
//	 			{
//	 				airPortObj=(AirPortConfiguration)session.getAttribute("airPortObj");
//	 			}
//
//	 				path1="jsps/datareference/airPortConfiguration.jsp";
//
//	 			user1=(User)userList1.get(ind);
//	 			airPortObj.setLineManager(user1);
//				session.setAttribute("airPortObj", airPortObj);
//			}
//			else if(search.equals("editair"))
//			{
//				AirPortConfiguration airPortObj=null;
//	 			if(session.getAttribute("airPortObjConfigConfiguration")==null)
//	 			{
//	 				airPortObj=new AirPortConfiguration();
//	 			}
//	 			else
//	 			{
//	 				airPortObj=(AirPortConfiguration)session.getAttribute("airPortObjConfigConfiguration");
//	 			}
//
//	 				path1="jsps/datareference/editAirportConfig.jsp";
//
//	 			user1=(User)userList1.get(ind);
//	 			airPortObj.setLineManager(user1);
//				session.setAttribute("airPortObjConfigConfiguration", airPortObj);
//			}
//			else if(search.equals("import"))
//			{
//				ImportPortConfiguration importPortObj=null;
//	 			if(session.getAttribute("importPortObj")==null)
//	 			{
//	 				importPortObj=new ImportPortConfiguration();
//	 			}
//	 			else
//	 			{
//	 				importPortObj=(ImportPortConfiguration)session.getAttribute("importPortObj");
//	 			}
//
//	 				path1="jsps/datareference/imports.jsp";
//
//	 			user1=(User)userList1.get(ind);
//	 			importPortObj.setLineManager(user1);
//				session.setAttribute("importPortObj", importPortObj);
//			}
//			else if(search.equals("editimport"))
//			{
//				ImportPortConfiguration importPortObj=null;
//	 			if(session.getAttribute("impPortObjConfiguration")==null)
//	 			{
//	 				importPortObj=new ImportPortConfiguration();
//	 			}
//	 			else
//	 			{
//	 				importPortObj=(ImportPortConfiguration)session.getAttribute("impPortObjConfiguration");
//	 			}
//
//	 				path1="jsps/datareference/editImportConfig.jsp";
//
//	 			user1=(User)userList1.get(ind);
//	 			importPortObj.setLineManager(user1);
//				session.setAttribute("impPortObjConfiguration", importPortObj);
//			}
//			else if(search.equals("warehouse"))
//			{
//				Warehouse warehouse=null;
//	 			if(session.getAttribute("warehouse")==null)
//	 			{
//	 				warehouse=new Warehouse();
//	 			}
//	 			else
//	 			{
//	 				warehouse=(Warehouse)session.getAttribute("warehouse");
//	 			}
//
//	 				path1="jsps/datareference/addWarehouse.jsp";
//
//	 			user1=(User)userList1.get(ind);
//	 			warehouse.setManager(user1);
//				session.setAttribute("warehouse", warehouse);
//			}
//			else if(search.equals("editwarehouse"))
//			{
//				Warehouse warehouse=null;
//	 			if(session.getAttribute("warehouse")==null)
//	 			{
//	 				warehouse=new Warehouse();
//	 			}
//	 			else
//	 			{
//	 				warehouse=(Warehouse)session.getAttribute("warehouse");
//	 			}
//
//	 				path1="jsps/datareference/editWarehouse.jsp";
//
//	 			user1=(User)userList1.get(ind);
//	 			warehouse.setManager(user1);
//				session.setAttribute("warehouse", warehouse);
//			}
//			request.setAttribute("path1", path1);
//			request.setAttribute("buttonValue", "completed");
		}
		else
		{
			if(buttonValue.equals("search"))
			{
				List userList=(List)userDAO.findLoginName1(loginName,lastName);
				session.setAttribute("userList",userList);
			}
		}
		
		return mapping.findForward("user");
	}
}