package com.gp.cong.logisoft.bc.tradingpartner;

public interface TradingPartnerConstants {

    String TRADINGPARTNER = "TRADINGPARTNER";
    String PARAMETER_NAME = "PARAMETER";
    String AP_ADDRESS = "APADDRESS";
    String LOAD_CONTACT_DETAILS = "loadContactDetails";
    String LOAD_INVOICE_ADDRESS_DETAILS = "loadInvoiceAddressDetails";
    String LOAD_PAYMENT_ADDRESS_DETAILS = "loadPaymentAddressDetails";
    String LOAD_MASTER_ADDRESS = "loadMasterAddress";
    String CUSTOMER_ADDRESS_DETAILS = "customerAddressDetails";
    String CUSTOMER_CONTACT_DETAILS = "customerContactDetails";
    String MASTER_ADDRESS_DETAILS = "masterAddressDetails";
    String ADD_CONTACT_DETAILS = "addContactDetails";
    String ADD_INVOICE_ADDRESS = "addInvoiceAddress";
    String ADD_PAYMENT_ADDRESS = "addPaymentAddress";
    String ADD_MASTER_ADDRESS = "addMasterAddress";
    String SAVE_ARCONFIGURATION = "saveARConfiguration";
    String ARCONFIGURATION_PAGE = "arConfigPage";
    String CUST_ADDRESS = "CUST_ADDRESS";
    String TRADINGPARTNER_FORM = "tradingPartnerForm";
    String ADD_ADDRESS = "ADD_ADDRESS";
    String TRADINGPARTNER_SEARCH_LIST = "tradingPartnerSearchList";
    String TRADINGPARTNER_MASTER_SEARCH_LIST = "tradingPartnerMasterSearchList";
    String SHOW_SUBSIDIARIERS = "showSubsidiaries";
    String SHOW_SUBSIDIARIERS_PAGE = "showSubsidiariesPage";
    String SHOW_CONSIGNEE_INFO_PAGE = "consigneeInfo";
    String SAVE_CONSIGNEE_INFO = "saveConsigneeInfo";
    String SAVE_CTS_INFO = "saveCtsInfo";
    String SHOW_CTS_INFO_PAGE = "ctsInfo";
    String SUBSIDIARIERS_LIST = "subsidiariesList";
    String VIEW = "view";
    String E1 = "E1";
    String E3 = "E3";
    String F1 = "F1";
    String F3 = "F3";
    String CREDITHOLD = "Credit Hold";
    String NOCREDIT = "No Credit";
    String IN_GOOD_STANDING = "In Good Standing";
    String SUSPENDED_SEE_ACCOUNTING = "Suspended/See Accounting";
    String LEGAL_SEE_ACCOUNTING = "Legal/See Accounting";
    //Acct Types;
    String SHIPPER = "S";
    String NOTIFY = "N";
    String CONSIGNEE = "C";
    String COMPANY = "Z";
    String IMPORT_AGENT = "I";
    String EXPORT_AGENT = "E";
    String VENDOR = "V";
    String OTHERS = "O";
    //Sub Types
    String AIR_LINE = "Air Line";
    String SUB_TYPE_SHIPPER = "Shipper";
    String FORWARDER = "Forwarder";
    String SUB_TYPE_CONSIGNEE = "Consignee";
    String OVERHEAD = "Overhead";
    String STEAMSHIP_LINE = "Steamship Line";
    String TRUCKER = "Trucker";
    String WAREHOUSE = "Warehouse";
    String SUB_TYPE_IMPORT_AGENT = "Import Agent";
    String SUB_TYPE_EXPORT_AGENT = "Export Agent";
    String SUB_TYPE_IMPORT_CFS = "Import CFS";
    String ECU_DESIGNATION_AGENTS = "AG";
    String ECU_DESIGNATION_INTERCOMPANY = "IC";
    String ECU_DESIGNATION_LOCAL = "LO";
}
