/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gp.cvst.logisoft.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gp.cong.logisoft.bc.fcl.FclBlBC;
import com.gp.cong.logisoft.bc.fcl.FclBlConstants;
import com.gp.cvst.logisoft.struts.form.FclBlCorrectionPopUpForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-10-2009
 * 
 * XDoclet definition:
 * @struts.action path="/fclBlCorrectionPopUp" name="fclBlCorrectionPopUpForm" input="/jsps/fclQuotes/fclBlCorrectionPopUp.jsp" scope="request" validate="true"
 */
public class FclBlCorrectionPopUpAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		FclBlCorrectionPopUpForm fclBlCorrectionPopUpForm = (FclBlCorrectionPopUpForm) form;// TODO Auto-generated method stub
		String buttonValue = fclBlCorrectionPopUpForm.getButtonValue();
		String bolNo = fclBlCorrectionPopUpForm.getBolNo();
		String forwardName="";
		FclBlBC FclBlBC=new FclBlBC();
		if(buttonValue!=null && buttonValue.equalsIgnoreCase("searchCorrection")){
			request.setAttribute(FclBlConstants.NOTICE_NO_LIST, FclBlBC.getCorrectionListForApprovedBl(bolNo));
			forwardName="fclBlCorrectionPopUp";
		}
		return mapping.findForward(forwardName);
	}
}