/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gp.cong.logisoft.struts.ratemangement.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/**
 * MyEclipse Struts Creation date: 03-21-2004
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loadFCLPopupForm"
 */
public class LoadFCLPopupForm extends ActionForm {
	private FormFile theFile;
	private String hiddenorigins;
	private String notinsert;

	public FormFile getTheFile(){
		return theFile;
	}

	public String getHiddenorigins() {
		return hiddenorigins;
	}

	public void setHiddenorigins(String hiddenorigins) {
		this.hiddenorigins = hiddenorigins;
	}

	public void setTheFile(FormFile theFile) {
		this.theFile = theFile;
	}

	public String getNotinsert() {
		return notinsert;
	}

	public void setNotinsert(String notinsert) {
		this.notinsert = notinsert;
	}

}