package com.gp.cvst.logisoft.domain;

/**
 * FiscalYear generated by MyEclipse - Hibernate Tools
 */
public class FiscalYear implements java.io.Serializable {

    // Fields    
    private Integer id;
    private Integer year;
    private String active;
    private String clsPeriod;
    private String adjPeriod;
    private String startPeriod;
    private String endPeriod;
    private transient String nextYearPeriod;

    // Constructors
    /**
     * default constructor
     */
    public FiscalYear() {
    }

    /**
     * full constructor
     */
    public FiscalYear(Integer year, String active, String clsPeriod, String adjPeriod) {
        this.year = year;
        this.active = active;
        this.clsPeriod = clsPeriod;
        this.adjPeriod = adjPeriod;
    }

    // Property accessors
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public String getClsPeriod() {
        return this.clsPeriod;
    }

    public void setClsPeriod(String clsPeriod) {
        this.clsPeriod = clsPeriod;
    }

    public String getAdjPeriod() {
        return this.adjPeriod;
    }

    public void setAdjPeriod(String adjPeriod) {
        this.adjPeriod = adjPeriod;
    }

    public String getStartPeriod() {
        return startPeriod;
    }

    public void setStartPeriod(String startPeriod) {
        this.startPeriod = startPeriod;
    }

    public String getEndPeriod() {
        return endPeriod;
    }

    public void setEndPeriod(String endPeriod) {
        this.endPeriod = endPeriod;
    }

    public String getNextYearPeriod() {
        return nextYearPeriod;
    }

    public void setNextYearPeriod(String nextYearPeriod) {
        this.nextYearPeriod = nextYearPeriod;
    }

}
