/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gp.cvst.logisoft.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.gp.cong.logisoft.bc.accounting.ReportConstants;
import com.logiware.form.EventForm;

/**
 * MyEclipse Struts Creation date: 08-20-2008
 *
 * XDoclet definition:
 *
 * @struts.form name="fclBillLaddingform"
 */
public class FclBillLaddingForm extends EventForm {
    /*
     * Generated Methods
     */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    //new columns added for importvesnam
    private String importAMSHosueBlNumber;
    private String importRelease;
    private String importReleaseComments;
    private String importVerifiedEta;
    private String blBy;
    private String printRev;
    //...Fcl Bl container form property....
    private String[] adjustment;//
    private String action;//
    private String adjustmentAmount;
    private String oldAmount;
    private String newMasterBL;
    private String confOnBoardComments;
    private String adminCost;
    private String differenceOfCostAndCharges;
    private String tempFFCostCOde;
    private String tempFAECostCOde;
    private String confirmOnBoard;
    private String verifyEta;
    private String trailerNo;
    private String trailerNoOld;
    private String sealNo;
    private String lastUpdate;
    private String sizeLegend;
    private String txtItemcreatedon1;
    private String index;
    private String trialCheckbox;
    private String marksNo;
    private String userName;
    private String chargeFlag;
    private String billToCode;
    private String containerComments;
    private String tempContainerComments;
    private String editAgentNameCheck;
    //===============end===============
//	Fcl Bl Cost and charges form property....
    private String rollUpAmount;
    private String[] charge;
    private String[] billTo;
    private String[] printBl;
    private String[] amount;
    private String total;
    private String billTrePty;
    private String readyToPostForCost;
    private String readyToPostCostCheck;
    private String readyToPostCheck;
    private String[] account;
    private String altAgent;
    private String index1;
    private String totalCosts;
    private String[] currency;
    private String portNo;
    private String rateByAgent;
    private String issuingTml;
    private String forwarderNo;
    private String shipperNo;
    private String ssNo;
    private String txtItemcreatedon;
    private String billThirdParty;
    private String billThirdPartyName;
    private String[] pcollect;
    private String[] pprepaid;
    private String chargesCheckAll;
    //----PROPERTIES OF FCLBL COSTS ------
    private String costCode;
    private String costCodeDesc;
    private String accountNo;
    private String costAmount;
    private String costCurrency;
    private String datePaid;
    private String costComments;
    private String chequeNumber;
    private String costCodeId;
    private String invoiceNumber;
    private String directConsignment;
    //===============end===============
    // new fields added
    private String masterForFreighted = ReportConstants.NO;
    private String masterForUnFreighted = ReportConstants.NO;
    private String originPrePrintedForFreighted = ReportConstants.NO;
    private String originPrePrintedForUnFreighted = ReportConstants.NO;
    ;
    private String doorOfOrigin;
    private String doorOfDestination;
    private String[] printCheck;
    private String blClause;
    private String clauseDescription;
    private String originalBL;
    private String fclInttgra;
    private String copyBol;
    private String accountName;
    private String ediCheckBox;
    private String houseName;
    private String auditCheckBox;
    private String consigneeName;
    private String masterCheckBox;
    private String houseConsigneeName;
    private String blColsed;
    private String notifyPartyName;
    private String AES;
    private String houseNotifyPartyName;
    private String fileType;
    private String notifyParty;
    // --------------
    private String buttonValue;
    private Integer bkgNo;
    private String billofladding;
    private String terminalName;
    private String masterBlNotes;
    private String billofdate;
    private String streamShipName;
    private String booking;
    private String sslinenumber;
    private String sailDate;
    private String portCutOff;
    private String docCutOff;
    private String earlierPickUpDate;
    private String eta;
    private String forwardingAgentName;
    private String agentAddress;
    private String originalTerminal;
    private Integer quote;
    private String billingTerminal;
    private String terminal;
    private String fileNo;
    private String masterBlComments;
    private String notifyPartySource;
    private String consigneeSource;
    private String shipperSource;
    private String port;
    private String sslinecarrier;
    private String readyToPost;
    private String shipmentType;
    private String portofladding;
    private String portofdischarge;
    private String vessel;
    private String vesselname;
    private String voyage;
    private String shipper;
    private String consignee;
    private String forwardingAgent;
    private String streamshipNotifyParty;
    private String streamshipLine;
    private String finalDestination;
    private String streamShipConsignee;
    private String houseShipper;
    private String houseShipper1;
    private String houseConsignee;
    private String houseConsignee1;
    private String houseNotifyParty;
    private String streamShipBL = "P";
    private String houseBL = "P";
    private String alternateAgent;
    private String imporigBL;
    private String forwardingAgent1;
    private String placeofReceipt;
    private String portofCountryandOrigin;
    private String forwardingAgentno;
    private String exportReference;
    private String domesticRouting;
    private String transshipmentTo;
    private String onwardInlandRouting;
    private String consolidationVoyage;
    private String hazmath;
    private String terminalId;
    private String portId;
    private String portIdLoading;
    private String portIdDischarge;
    private String carrierId;
    private String streamShip;
    private String quotesId;
    private String bookingId;
    private String vesselId;
    private String voyageId;
    private String hazmat = "N";
    private String streamshipLineNo;
    private String streamshipLineName;
    private String OPrinting = "Yes";
    private String NPrinting = "Yes";
    private String BLPrinting = "Yes";
    private String preCarriage;
    private String placeOfReceipt;
    private String loadingPier;
    private String noOfOriginals;
    private String insurance;
    private String insuranceRate;
    private String costOfGoods;
    private String houseNotifyPartyaddress;
    private String toprintCharges;
    private String bol;
    private String ssBldestinationChargesPreCol;
    private String importsFreightRelease = ReportConstants.NO;
    private String printCorrected = "Yes";
    private String etaFd;
    // ---new fields added for Print section---
    private String agentsForCarrier;
    private String shipperLoadsAndCounts;
    private String printContainersOnBL;
    private String conturyOfOrigin;
    private String alternatePOL = ReportConstants.NO;
    private String noOfPackages;
    private String proof;
    private String preAlert;
    private String nonNegotiable;
    private String doorOriginAsPlor;
    private String doorOriginAsPlorHouse;
    private String doorDestinationAsFinalDeliveryToHouse;
    private String doorDestinationAsFinalDeliveryToMaster;
    private String trimTrailingZerosForQty;
    private String collectThirdParty;
    private String printAlternatePort;
    private String bundleIntoOfr;
    private String originalBlRequired = ReportConstants.NO;
    private String destinationChargesPreCol = "C";
    private String printPhrase = ReportConstants.NO;
    private String manifestPrintReport = ReportConstants.NO;
    private String totalContainers = ReportConstants.NO;
    private String houseFreightedBL = ReportConstants.NO;
    private String freightInvoice = ReportConstants.NO;
    private String houseFreightedNNBL = ReportConstants.NO;
    private String houseFreightedOriginal = ReportConstants.NO;
    private String houseUnFreightedBL = ReportConstants.NO;
    private String houseUnFreightedNNBL = ReportConstants.NO;
    private String houseUnFreightedOriginal = ReportConstants.NO;
    private String steamShipMaster = ReportConstants.NO;
    private String manifest = ReportConstants.NO;
    private String houseFreightInvoice = ReportConstants.NO;
    private String confirmOnBoardNotice = ReportConstants.NO;
    private String fclArrivalNotice = ReportConstants.NO;
    private String importArrivalNotice = ReportConstants.NO;
    private String freightNonNego = ReportConstants.NO;
    private String unFreightNonNego = ReportConstants.NO;
    private String omitTermAndPort = ReportConstants.NO;
    private String replaceArrival = ReportConstants.NO;
    private String hblPOLOverride = ReportConstants.NO;
    private String hblPODOverride = ReportConstants.NO;
    private String hblFDOverride = ReportConstants.NO;
    private String serviceContractNo = ReportConstants.YES;
    private String certifiedTrueCopy = ReportConstants.NO;
    private String alternateNoOfPackages;
    //2 new fields
    private String agent;
    private String agentNo;
    private String defaultAgent;
    private String quoteBy;
    private String quoteDate;
    private String bookingBy;
    private String bookingDate;
    private String billToParty;
    //new fields added for trade route
    private String moveType;
    private String zip;
    private String rampCity;
    private String noOfDays;
    private String routedByAgent;
    private String country;
    private String portremarks;
    private String commodityCode;
    private String commodityDesc;
    private String routedAgentCheck;
    // private String portremarks1;
    private String vaoyageInternational;
    private String ratesRemarks;
    private String setFocus;
    private String lineMove;
    private String latestBolId;
    //temp property to maintain jquery tabs-----
    private String selectedTab;
    private String autoDeductFFCom;
    // for fclcharges added by shanmugam
    private String chargeCode;
    private String chargeCodeDesc;
    private String chargeAmount;
    private String chargeBillTo;
    private String chargePrintBl;
    private String chargeCurrency;
    private String chargeId;
    private String chargesRemarks;
    private String adjustmentChargesRemarks;
    private boolean adjustmentToAllContainer;
    //to save the checkboxes that disable dojo
    private String masterConsigneeCheck;
    private String masterNotifyCheck;
    private String consigneeCheck;
    private String houseShipperCheck;
    private String editHouseShipperCheck;
    private String editHouseNotifyCheck;
    private String editHouseConsigneeCheck;
    private String ediConsigneeCheck;
    private String ediShipperCheck;
    private String ediNotifyPartyCheck;
    private String notifyCheck;
    private String dateInYard;
    private String dateOutYard;
    //inbond details
    private String inbondNumber;
    private String inbondDate;
    private String inbondPort;
    private String checkNumber;
    private String amountAndPaidBy;
    private String paymentRelease = "N";
    private String paymentReleasedOn;
    private String paymentReleaseComments;
    private String paymentAmount;
    private String manualChargeAmount;
    private String editFlag;
    private String alternatePort;
    private String aesStatus;
    private String trnref;
    private String fclSsblGoCollect;
    private String ratesNonRates;
    private String breakBulk;
    private String hblPOL;
    private String hblPOD;
    private String hblFD;

    /* for notes */
    private String oldCost;
    private String oldVendor;
    private String oldVendorName;
    private String vendorName;
    private String vendorNumber;
    private String oldComment;
    private String comment;
    private String oldCostCode;
    private String oldCostCodeDesc;
    private String vendorCheckBox;
    private String nvoCheckBox;
    private String transferCost;
    private String transactionRefId;
    //Import WareHouse Fields
    private String importWareHouseName;
    private String importWareHouseCode;
    private String importWareHouseAddress;
    private String importPickUpRemarks;
    private String internalRemark;
    //vessel Check
    private String vesselNameCheck;
    private String manualVesselName;
    private String trailerNoId;
    private String dockReceipt = ReportConstants.DOCKRECEIPTOPTION;
    private String manuallyAddedFlag;
    private String resendCostToBlue;
    private String brand;
    private String freightInvoiceContacts;

    public String getImportPickUpRemarks() {
        return importPickUpRemarks;
    }

    public void setImportPickUpRemarks(String importPickUpRemarks) {
        this.importPickUpRemarks = importPickUpRemarks;
    }

    public String getImportWareHouseAddress() {
        return importWareHouseAddress;
    }

    public void setImportWareHouseAddress(String importWareHouseAddress) {
        this.importWareHouseAddress = importWareHouseAddress;
    }

    public String getImportWareHouseCode() {
        return importWareHouseCode;
    }

    public void setImportWareHouseCode(String importWareHouseCode) {
        this.importWareHouseCode = importWareHouseCode;
    }

    public String getImportWareHouseName() {
        return importWareHouseName;
    }

    public void setImportWareHouseName(String importWareHouseName) {
        this.importWareHouseName = importWareHouseName;
    }

    public String getTransactionRefId() {
        return transactionRefId;
    }

    public void setTransactionRefId(String transactionRefId) {
        this.transactionRefId = transactionRefId;
    }

    public String getBreakBulk() {
        return breakBulk;
    }

    public void setBreakBulk(String breakBulk) {
        this.breakBulk = breakBulk;
    }

    public String getRatesNonRates() {
        return ratesNonRates;
    }

    public void setRatesNonRates(String ratesNonRates) {
        this.ratesNonRates = ratesNonRates;
    }

    public String getEditFlag() {
        return editFlag;
    }

    public void setEditFlag(String editFlag) {
        this.editFlag = editFlag;
    }

    public String getManualChargeAmount() {
        return manualChargeAmount;
    }

    public void setManualChargeAmount(String manualChargeAmount) {
        this.manualChargeAmount = manualChargeAmount;
    }

    public String getPaymentAmount() {
        return paymentAmount;
    }

    public void setPaymentAmount(String paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    public String getPaymentReleaseComments() {
        return paymentReleaseComments;
    }

    public void setPaymentReleaseComments(String paymentReleaseComments) {
        this.paymentReleaseComments = paymentReleaseComments;
    }

    public String getPaymentReleasedOn() {
        return paymentReleasedOn;
    }

    public void setPaymentReleasedOn(String paymentReleasedOn) {
        this.paymentReleasedOn = paymentReleasedOn;
    }

    public String getPaymentRelease() {
        return paymentRelease;
    }

    public void setPaymentRelease(String paymentRelease) {
        this.paymentRelease = paymentRelease;
    }

    public String getAmountAndPaidBy() {
        return amountAndPaidBy;
    }

    public void setAmountAndPaidBy(String amountAndPaidBy) {
        this.amountAndPaidBy = amountAndPaidBy;
    }

    public String getCheckNumber() {
        return checkNumber;
    }

    public void setCheckNumber(String checkNumber) {
        this.checkNumber = checkNumber;
    }

    public void setPrintRev(String printRev) {
        this.printRev = printRev;
    }

    public String getPrintRev() {
        return printRev;
    }

    public String getBlBy() {
        return blBy;
    }

    public void setBlBy(String blBy) {
        this.blBy = blBy;
    }
    //	newly added feilds..

    public String getDateInYard() {
        return dateInYard;
    }

    public void setDateInYard(String dateInYard) {
        this.dateInYard = dateInYard;
    }

    public String getDateOutYard() {
        return dateOutYard;
    }

    public void setDateOutYard(String dateOutYard) {
        this.dateOutYard = dateOutYard;
    }

    public String getConsigneeCheck() {
        return consigneeCheck;
    }

    public void setConsigneeCheck(String consigneeCheck) {
        this.consigneeCheck = consigneeCheck;
    }

    public String getMasterConsigneeCheck() {
        return masterConsigneeCheck;
    }

    public void setMasterConsigneeCheck(String masterConsigneeCheck) {
        this.masterConsigneeCheck = masterConsigneeCheck;
    }

    public String getMasterNotifyCheck() {
        return masterNotifyCheck;
    }

    public void setMasterNotifyCheck(String masterNotifyCheck) {
        this.masterNotifyCheck = masterNotifyCheck;
    }

    public String getNotifyCheck() {
        return notifyCheck;
    }

    public void setNotifyCheck(String notifyCheck) {
        this.notifyCheck = notifyCheck;
    }

    public String getSetFocus() {
        return setFocus;
    }

    public void setSetFocus(String setFocus) {
        this.setFocus = setFocus;
    }

    public String getRatesRemarks() {
        return ratesRemarks;
    }

    public void setRatesRemarks(String ratesRemarks) {
        this.ratesRemarks = ratesRemarks;
    }

    public String getVaoyageInternational() {
        return vaoyageInternational;
    }

    public void setVaoyageInternational(String vaoyageInternational) {
        this.vaoyageInternational = vaoyageInternational;
    }

    public String getPortremarks() {
        return portremarks;
    }

    public void setPortremarks(String portremarks) {
        this.portremarks = portremarks;
    }

    /*	public String getPortremarks1() {
     return portremarks1;
     }

     public void setPortremarks1(String portremarks1) {
     this.portremarks1 = portremarks1;
     }*/
    public String getCountry() {
        return null != country ? country.toUpperCase() : "";
    }

    public void setCountry(String country) {
        this.country = null != country ? country.toUpperCase() : "";
    }

    public String getRoutedByAgent() {
        return routedByAgent;
    }

    public void setRoutedByAgent(String routedByAgent) {
        this.routedByAgent = routedByAgent;
    }

    public String getMoveType() {
        return moveType;
    }

    public void setMoveType(String moveType) {
        this.moveType = moveType;
    }

    public String getNoOfDays() {
        return noOfDays;
    }

    public void setNoOfDays(String noOfDays) {
        this.noOfDays = noOfDays;
    }

    public String getRampCity() {
        return rampCity;
    }

    public void setRampCity(String rampCity) {
        this.rampCity = rampCity;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getBillToParty() {
        return billToParty;
    }

    public void setBillToParty(String billToParty) {
        this.billToParty = billToParty;
    }

    public String getAgent() {
        return agent;
    }

    public void setAgent(String agent) {
        this.agent = agent;
    }

    public String getAgentNo() {
        return agentNo;
    }

    public void setAgentNo(String agentNo) {
        this.agentNo = agentNo;
    }

    public String getDestinationChargesPreCol() {
        return destinationChargesPreCol;
    }

    public void setDestinationChargesPreCol(String destinationChargesPreCol) {
        this.destinationChargesPreCol = destinationChargesPreCol;
    }

    public String getOriginalBlRequired() {
        return originalBlRequired;
    }

    public void setOriginalBlRequired(String originalBlRequired) {
        this.originalBlRequired = originalBlRequired;
    }

    public String getBol() {
        return bol;
    }

    public void setBol(String bol) {
        this.bol = bol;
    }

    public String getToprintCharges() {
        return toprintCharges;
    }

    public void setToprintCharges(String toprintCharges) {
        this.toprintCharges = toprintCharges;
    }

    public String getHouseNotifyPartyaddress() {
        return null != houseNotifyPartyaddress ? houseNotifyPartyaddress.toUpperCase() : "";
    }

    public void setHouseNotifyPartyaddress(String houseNotifyPartyaddress) {
        this.houseNotifyPartyaddress = null != houseNotifyPartyaddress ? houseNotifyPartyaddress.toUpperCase() : "";
    }

    public String getNoOfOriginals() {
        return noOfOriginals;
    }

    public void setNoOfOriginals(String noOfOriginals) {
        this.noOfOriginals = noOfOriginals;
    }

    public String getHazmat() {
        return hazmat;
    }

    public void setHazmat(String hazmat) {
        this.hazmat = hazmat;
    }

    public String getStreamShip() {
        return null != streamShip ? streamShip.toUpperCase() : "";
    }

    public void setStreamShip(String streamShip) {
        this.streamShip = null != streamShip ? streamShip.toUpperCase() : "";
    }

    public String getCarrierId() {
        return carrierId;
    }

    public void setCarrierId(String carrierId) {
        this.carrierId = carrierId;
    }

    public String getPortIdDischarge() {
        return portIdDischarge;
    }

    public void setPortIdDischarge(String portIdDischarge) {
        this.portIdDischarge = portIdDischarge;
    }

    public String getPortIdLoading() {
        return portIdLoading;
    }

    public void setPortIdLoading(String portIdLoading) {
        this.portIdLoading = portIdLoading;
    }

    public String getPortId() {
        return portId;
    }

    public void setPortId(String portId) {
        this.portId = portId;
    }

    public String getTerminalId() {
        return terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    public String getHazmath() {
        return hazmath;
    }

    public void setHazmath(String hazmath) {
        this.hazmath = hazmath;
    }

    public String getHouseConsignee() {
        return null != houseConsignee ? houseConsignee.toUpperCase() : "";
    }

    public void setHouseConsignee(String houseConsignee) {
        this.houseConsignee = null != houseConsignee ? houseConsignee.toUpperCase() : "";
    }

    public String getHouseConsignee1() {
        return null != houseConsignee1 ? houseConsignee1.toUpperCase() : "";
    }

    public void setHouseConsignee1(String houseConsignee1) {
        this.houseConsignee1 = null != houseConsignee1 ? houseConsignee1.toUpperCase() : "";
    }

    public String getHouseNotifyParty() {
        return null != houseNotifyParty ? houseNotifyParty.toUpperCase() : "";
    }

    public void setHouseNotifyParty(String houseNotifyParty) {
        this.houseNotifyParty = null != houseNotifyParty ? houseNotifyParty.toUpperCase() : "";
    }

    public String getHouseShipper() {
        return null != houseShipper ? houseShipper.toUpperCase() : "";
    }

    public void setHouseShipper(String houseShipper) {
        this.houseShipper = null != houseShipper ? houseShipper.toUpperCase() : "";
    }

    public String getHouseShipper1() {
        return null != houseShipper1 ? houseShipper1.toUpperCase() : "";
    }

    public void setHouseShipper1(String houseShipper1) {
        this.houseShipper1 = null != houseShipper1 ? houseShipper1.toUpperCase() : "";
    }

    public String getStreamShipConsignee() {
        return null != streamShipConsignee ? streamShipConsignee.toUpperCase() : "";
    }

    public void setStreamShipConsignee(String streamShipConsignee) {
        this.streamShipConsignee = null != streamShipConsignee ? streamShipConsignee.toUpperCase() : "";
    }

    public String getButtonValue() {
        return buttonValue;
    }

    public void setButtonValue(String buttonValue) {
        this.buttonValue = buttonValue;
    }

    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    public String getBillofdate() {
        return billofdate;
    }

    public void setBillofdate(String billofdate) {
        this.billofdate = billofdate;
    }

    public String getBillofladding() {
        return billofladding;
    }

    public void setBillofladding(String billofladding) {
        this.billofladding = billofladding;
    }

    public String getForwardingAgent() {
        return forwardingAgent;
    }

    public void setForwardingAgent(String forwardingAgent) {
        this.forwardingAgent = forwardingAgent;
    }

    public String getPort() {
        return port;
    }

    public void setPort(String port) {
        this.port = port;
    }

    public String getPortofladding() {
        return portofladding;
    }

    public void setPortofladding(String portofladding) {
        this.portofladding = portofladding;
    }

    public String getPortofdischarge() {
        return portofdischarge;
    }

    public void setPortofdischarge(String portofdischarge) {
        this.portofdischarge = portofdischarge;
    }

    /*	public Integer getBooking() {
     return booking;
     }

     public void setBooking(String booking) {
     int duplicate = Integer.parseInt(booking);
     this.booking = duplicate;
     }*/
    public Integer getQuote() {
        return quote;
    }

    public void setQuote(Integer quote) {
        this.quote = quote;
    }

    public String getSslinecarrier() {
        return sslinecarrier;
    }

    public void setSslinecarrier(String sslinecarrier) {
        this.sslinecarrier = sslinecarrier;
    }

    public String getConsignee() {
        return null != consignee ? consignee.toUpperCase() : "";
    }

    public void setConsignee(String consignee) {
        this.consignee = null != consignee ? consignee.toUpperCase() : "";
    }

    public String getShipper() {
        return null != shipper ? shipper.toUpperCase() : "";
    }

    public void setShipper(String shipper) {
        this.shipper = null != shipper ? shipper.toUpperCase() : "";
    }

    public String getStreamshipLine() {
        return streamshipLine;
    }

    public void setStreamshipLine(String streamshipLine) {
        this.streamshipLine = streamshipLine;
    }

    public String getStreamshipNotifyParty() {
        return null != streamshipNotifyParty ? streamshipNotifyParty.toUpperCase() : "";
    }

    public void setStreamshipNotifyParty(String streamshipNotifyParty) {
        this.streamshipNotifyParty = null != streamshipNotifyParty ? streamshipNotifyParty.toUpperCase() : "";
    }

    public String getTerminal() {
        return terminal;
    }

    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    public String getVessel() {
        return vessel;
    }

    public void setVessel(String vessel) {
        this.vessel = vessel;
    }

    public String getVesselname() {
        return vesselname;
    }

    public void setVesselname(String vesselname) {
        this.vesselname = vesselname;
    }

    public String getVoyage() {
        return null != voyage ? voyage.toUpperCase() : "";
    }

    public void setVoyage(String voyage) {
        this.voyage = null != voyage ? voyage.toUpperCase() : "";
    }

    public String getHouseBL() {
        return houseBL;
    }

    public void setHouseBL(String houseBL) {
        this.houseBL = houseBL;
    }

    public String getStreamShipBL() {
        return streamShipBL;
    }

    public void setStreamShipBL(String streamShipBL) {
        this.streamShipBL = streamShipBL;
    }

    public String getDomesticRouting() {
        return domesticRouting;
    }

    public void setDomesticRouting(String domesticRouting) {
        this.domesticRouting = domesticRouting;
    }

    public String getExportReference() {
        return null != exportReference ? exportReference.toUpperCase() : "";
    }

    public void setExportReference(String exportReference) {
        this.exportReference = null != exportReference ? exportReference.toUpperCase() : "";
    }

    public String getForwardingAgent1() {
        return null != forwardingAgent1 ? forwardingAgent1.toUpperCase() : "";
    }

    public void setForwardingAgent1(String forwardingAgent1) {
        this.forwardingAgent1 = null != forwardingAgent1 ? forwardingAgent1.toUpperCase() : "";
    }

    public String getForwardingAgentno() {
        return null != forwardingAgentno ? forwardingAgentno.toUpperCase() : "";
    }

    public void setForwardingAgentno(String forwardingAgentno) {
        this.forwardingAgentno = null != forwardingAgentno ? forwardingAgentno.toUpperCase() : "";
    }

    public String getPlaceofReceipt() {
        return placeofReceipt;
    }

    public void setPlaceofReceipt(String placeofReceipt) {
        this.placeofReceipt = placeofReceipt;
    }

    public String getAlternateAgent() {
        return alternateAgent;
    }

    public void setAlternateAgent(String alternateAgent) {
        this.alternateAgent = alternateAgent;
    }

    public String getImporigBL() {
        return null != imporigBL ? imporigBL.toUpperCase() : "";
    }

    public void setImporigBL(String imporigBL) {
        this.imporigBL = null != imporigBL ? imporigBL.toUpperCase() : "";
    }

    public String getPortofCountryandOrigin() {
        return portofCountryandOrigin;
    }

    public void setPortofCountryandOrigin(String portofCountryandOrigin) {
        this.portofCountryandOrigin = portofCountryandOrigin;
    }

    public String getTransshipmentTo() {
        return transshipmentTo;
    }

    public void setTransshipmentTo(String transshipmentTo) {
        this.transshipmentTo = transshipmentTo;
    }

    public String getConsolidationVoyage() {
        return consolidationVoyage;
    }

    public void setConsolidationVoyage(String consolidationVoyage) {
        this.consolidationVoyage = consolidationVoyage;
    }

    public String getOnwardInlandRouting() {
        return null != onwardInlandRouting ? onwardInlandRouting.toUpperCase() : "";
    }

    public void setOnwardInlandRouting(String onwardInlandRouting) {
        this.onwardInlandRouting = null != onwardInlandRouting ? onwardInlandRouting.toUpperCase() : "";
    }

    public String getVesselId() {
        return vesselId;
    }

    public void setVesselId(String vesselId) {
        this.vesselId = vesselId;
    }

    public String getStreamshipLineName() {
        return streamshipLineName;
    }

    public void setStreamshipLineName(String streamshipLineName) {
        this.streamshipLineName = streamshipLineName;
    }

    public String getStreamshipLineNo() {
        return streamshipLineNo;
    }

    public void setStreamshipLineNo(String streamshipLineNo) {
        this.streamshipLineNo = streamshipLineNo;
    }

    public String getQuotesId() {
        return quotesId;
    }

    public void setQuotesId(String quotesId) {
        this.quotesId = quotesId;
    }

    public String getBookingId() {
        return bookingId;
    }

    public void setBookingId(String bookingId) {
        this.bookingId = bookingId;
    }

    public String getVoyageId() {
        return voyageId;
    }

    public void setVoyageId(String voyageId) {
        this.voyageId = voyageId;
    }

    public String getFinalDestination() {
        return finalDestination;
    }

    public void setFinalDestination(String finalDestination) {
        this.finalDestination = finalDestination;
    }

    public String getReadyToPost() {
        return readyToPost;
    }

    public void setReadyToPost(String readyToPost) {
        this.readyToPost = readyToPost;
    }

    public String getShipmentType() {
        return shipmentType;
    }

    public void setShipmentType(String shipmentType) {
        this.shipmentType = shipmentType;
    }

    public String getAgentAddress() {
        return agentAddress;
    }

    public void setAgentAddress(String agentAddress) {
        this.agentAddress = agentAddress;
    }

    public String getSailDate() {
        return sailDate;
    }

    public void setSailDate(String sailDate) {
        this.sailDate = sailDate;
    }

    public String getPreCarriage() {
        return preCarriage;
    }

    public void setPreCarriage(String preCarriage) {
        this.preCarriage = preCarriage;
    }

    public String getLoadingPier() {
        return loadingPier;
    }

    public void setLoadingPier(String loadingPier) {
        this.loadingPier = loadingPier;
    }

    public String getPlaceOfReceipt() {
        return placeOfReceipt;
    }

    public void setPlaceOfReceipt(String placeOfReceipt) {
        this.placeOfReceipt = placeOfReceipt;
    }

    public String getOPrinting() {
        return OPrinting;
    }

    public void setOPrinting(String printing) {
        OPrinting = printing;
    }

    public String getNPrinting() {
        return NPrinting;
    }

    public void setNPrinting(String printing) {
        NPrinting = printing;
    }

    public String getBLPrinting() {
        return BLPrinting;
    }

    public void setBLPrinting(String printing) {
        BLPrinting = printing;
    }

    public String getNotifyPartySource() {
        return notifyPartySource;
    }

    public void setNotifyPartySource(String notifyPartySource) {
        this.notifyPartySource = notifyPartySource;
    }

    public String getConsigneeSource() {
        return consigneeSource;
    }

    public void setConsigneeSource(String consigneeSource) {
        this.consigneeSource = consigneeSource;
    }

    public String getShipperSource() {
        return shipperSource;
    }

    public void setShipperSource(String shipperSource) {
        this.shipperSource = shipperSource;
    }

    public String getMasterBlComments() {
        return masterBlComments;
    }

    public void setMasterBlComments(String masterBlComments) {
        this.masterBlComments = masterBlComments;
    }

    public String getMasterBlNotes() {
        return masterBlNotes;
    }

    public void setMasterBlNotes(String masterBlNotes) {
        this.masterBlNotes = masterBlNotes;
    }

    public String getImportsFreightRelease() {
        return importsFreightRelease;
    }

    public void setImportsFreightRelease(String importsFreightRelease) {
        this.importsFreightRelease = importsFreightRelease;
    }

    public String getAuditCheckBox() {
        return auditCheckBox;
    }

    public void setAuditCheckBox(String auditCheckBox) {
        this.auditCheckBox = auditCheckBox;
    }

    public String getEdiCheckBox() {
        return ediCheckBox;
    }

    public void setEdiCheckBox(String ediCheckBox) {
        this.ediCheckBox = ediCheckBox;
    }

    public String getMasterCheckBox() {
        return masterCheckBox;
    }

    public void setMasterCheckBox(String masterCheckBox) {
        this.masterCheckBox = masterCheckBox;
    }

    public String getFclInttgra() {
        return fclInttgra;
    }

    public void setFclInttgra(String fclInttgra) {
        this.fclInttgra = fclInttgra;
    }

    public String getBlColsed() {
        return blColsed;
    }

    public void setBlColsed(String blColsed) {
        this.blColsed = blColsed;
    }

    public String getAES() {
        return AES;
    }

    public void setAES(String aes) {
        AES = aes;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getAccountName() {
        return null != accountName ? accountName.toUpperCase() : "";
    }

    public void setAccountName(String accountName) {
        this.accountName = null != accountName ? accountName.toUpperCase() : "";
    }

    public String getHouseName() {
        return null != houseName ? houseName.toUpperCase() : "";
    }

    public void setHouseName(String houseName) {
        this.houseName = null != houseName ? houseName.toUpperCase() : "";
    }

    public String getConsigneeName() {
        return null != consigneeName ? consigneeName.toUpperCase() : "";
    }

    public void setConsigneeName(String consigneeName) {
        this.consigneeName = null != consigneeName ? consigneeName.toUpperCase() : "";
    }

    public String getHouseConsigneeName() {
        return null != houseConsigneeName ? houseConsigneeName.toUpperCase() : "";
    }

    public void setHouseConsigneeName(String houseConsigneeName) {
        this.houseConsigneeName = null != houseConsigneeName ? houseConsigneeName.toUpperCase() : "";
    }

    public String getNotifyPartyName() {
        return null != notifyPartyName ? notifyPartyName.toUpperCase() : "";
    }

    public void setNotifyPartyName(String notifyPartyName) {
        this.notifyPartyName = null != notifyPartyName ? notifyPartyName.toUpperCase() : "";
    }

    public String getHouseNotifyPartyName() {
        return null != houseNotifyPartyName ? houseNotifyPartyName.toUpperCase() : "";
    }

    public void setHouseNotifyPartyName(String houseNotifyPartyName) {
        this.houseNotifyPartyName = null != houseNotifyPartyName ? houseNotifyPartyName.toUpperCase() : "";
    }

    public String getNotifyParty() {
        return null != notifyParty ? notifyParty.toUpperCase() : "";
    }

    public void setNotifyParty(String notifyParty) {
        this.notifyParty = null != notifyParty ? notifyParty.toUpperCase() : "";
    }

    public Integer getBkgNo() {
        return bkgNo;
    }

    public void setBkgNo(Integer bkgNo) {
        this.bkgNo = bkgNo;
    }

    public String getTerminalName() {
        return terminalName;
    }

    public void setTerminalName(String terminalName) {
        this.terminalName = terminalName;
    }

    public String getStreamShipName() {
        return streamShipName;
    }

    public void setStreamShipName(String streamShipName) {
        this.streamShipName = streamShipName;
    }

    public String getSslinenumber() {
        return sslinenumber;
    }

    public void setSslinenumber(String sslinenumber) {
        this.sslinenumber = sslinenumber;
    }

    public String getForwardingAgentName() {
        return null != forwardingAgentName ? forwardingAgentName.toUpperCase() : "";
    }

    public void setForwardingAgentName(String forwardingAgentName) {
        this.forwardingAgentName = null != forwardingAgentName ? forwardingAgentName.toUpperCase() : "";
    }

    public String getOriginalTerminal() {
        return originalTerminal;
    }

    public void setOriginalTerminal(String originalTerminal) {
        this.originalTerminal = originalTerminal;
    }

    public String getBillingTerminal() {
        return billingTerminal;
    }

    public void setBillingTerminal(String billingTerminal) {
        this.billingTerminal = billingTerminal;
    }

    public String getFileNo() {
        return fileNo;
    }

    public void setFileNo(String fileNo) {
        this.fileNo = fileNo;
    }

    public String getCopyBol() {
        return copyBol;
    }

    public void setCopyBol(String copyBol) {
        this.copyBol = copyBol;
    }

    public String getBlClause() {
        return blClause;
    }

    public void setBlClause(String blClause) {
        this.blClause = blClause;
    }

    public String getClauseDescription() {
        return clauseDescription;
    }

    public void setClauseDescription(String clauseDescription) {
        this.clauseDescription = clauseDescription;
    }

    public String getPrintContainersOnBL() {
        return printContainersOnBL;
    }

    public void setPrintContainersOnBL(String printContainersOnBL) {
        this.printContainersOnBL = printContainersOnBL;
    }

    public String getShipperLoadsAndCounts() {
        return shipperLoadsAndCounts;
    }

    public void setShipperLoadsAndCounts(String shipperLoadsAndCounts) {
        this.shipperLoadsAndCounts = shipperLoadsAndCounts;
    }

    public String getPrintPhrase() {
        return printPhrase;
    }

    public void setPrintPhrase(String printPhrase) {
        this.printPhrase = printPhrase;
    }

    public String getAgentsForCarrier() {
        return agentsForCarrier;
    }

    public void setAgentsForCarrier(String agentsForCarrier) {
        this.agentsForCarrier = agentsForCarrier;
    }

    public String getAlternatePOL() {
        return alternatePOL;
    }

    public void setAlternatePOL(String alternatePOL) {
        this.alternatePOL = alternatePOL;
    }

    public String getManifestPrintReport() {
        return manifestPrintReport;
    }

    public void setManifestPrintReport(String manifestPrintReport) {
        this.manifestPrintReport = manifestPrintReport;
    }

    public String getHouseFreightedBL() {
        return houseFreightedBL;
    }

    public void setHouseFreightedBL(String houseFreightedBL) {
        this.houseFreightedBL = houseFreightedBL;
    }

    public String getHouseFreightedNNBL() {
        return houseFreightedNNBL;
    }

    public void setHouseFreightedNNBL(String houseFreightedNNBL) {
        this.houseFreightedNNBL = houseFreightedNNBL;
    }

    public String getHouseFreightedOriginal() {
        return houseFreightedOriginal;
    }

    public void setHouseFreightedOriginal(String houseFreightedOriginal) {
        this.houseFreightedOriginal = houseFreightedOriginal;
    }

    public String getHouseUnFreightedBL() {
        return houseUnFreightedBL;
    }

    public void setHouseUnFreightedBL(String houseUnFreightedBL) {
        this.houseUnFreightedBL = houseUnFreightedBL;
    }

    public String getHouseUnFreightedNNBL() {
        return houseUnFreightedNNBL;
    }

    public void setHouseUnFreightedNNBL(String houseUnFreightedNNBL) {
        this.houseUnFreightedNNBL = houseUnFreightedNNBL;
    }

    public String getHouseUnFreightedOriginal() {
        return houseUnFreightedOriginal;
    }

    public void setHouseUnFreightedOriginal(String houseUnFreightedOriginal) {
        this.houseUnFreightedOriginal = houseUnFreightedOriginal;
    }

    public String getSteamShipMaster() {
        return steamShipMaster;
    }

    public void setSteamShipMaster(String steamShipMaster) {
        this.steamShipMaster = steamShipMaster;
    }

    public String getManifest() {
        return manifest;
    }

    public void setManifest(String manifest) {
        this.manifest = manifest;
    }

    public String getHouseFreightInvoice() {
        return houseFreightInvoice;
    }

    public void setHouseFreightInvoice(String houseFreightInvoice) {
        this.houseFreightInvoice = houseFreightInvoice;
    }

    public String getConfirmOnBoardNotice() {
        return confirmOnBoardNotice;
    }

    public void setConfirmOnBoardNotice(String confirmOnBoardNotice) {
        this.confirmOnBoardNotice = confirmOnBoardNotice;
    }

    public String getFclArrivalNotice() {
        return fclArrivalNotice;
    }

    public void setFclArrivalNotice(String fclArrivalNotice) {
        this.fclArrivalNotice = fclArrivalNotice;
    }

    public String getImportArrivalNotice() {
        return importArrivalNotice;
    }

    public void setImportArrivalNotice(String importArrivalNotice) {
        this.importArrivalNotice = importArrivalNotice;
    }

    public String getDefaultAgent() {
        return defaultAgent;
    }

    public void setDefaultAgent(String defaultAgent) {
        this.defaultAgent = defaultAgent;
    }

    public String getQuoteBy() {
        return quoteBy;
    }

    public void setQuoteBy(String quoteBy) {
        this.quoteBy = quoteBy;
    }

    public String getBookingBy() {
        return bookingBy;
    }

    public void setBookingBy(String bookingBy) {
        this.bookingBy = bookingBy;
    }

    public String getBookingDate() {
        return bookingDate;
    }

    public void setBookingDate(String bookingDate) {
        this.bookingDate = bookingDate;
    }

    public String getQuoteDate() {
        return quoteDate;
    }

    public void setQuoteDate(String quoteDate) {
        this.quoteDate = quoteDate;
    }

    public String getOriginalBL() {
        return originalBL;
    }

    public void setOriginalBL(String originalBL) {
        this.originalBL = originalBL;
    }

    public String getSsBldestinationChargesPreCol() {
        return ssBldestinationChargesPreCol;
    }

    public void setSsBldestinationChargesPreCol(String ssBldestinationChargesPreCol) {
        this.ssBldestinationChargesPreCol = ssBldestinationChargesPreCol;
    }

    public String getPrintCorrected() {
        return printCorrected;
    }

    public void setPrintCorrected(String printCorrected) {
        this.printCorrected = printCorrected;
    }

    public String getBooking() {
        return null != booking ? booking.toUpperCase() : "";
    }

    public void setBooking(String booking) {
        this.booking = null != booking ? booking.toUpperCase() : "";
    }

    public String getFreightInvoice() {
        return freightInvoice;
    }

    public void setFreightInvoice(String freightInvoice) {
        this.freightInvoice = freightInvoice;
    }

    public String getFreightNonNego() {
        return freightNonNego;
    }

    public void setFreightNonNego(String freightNonNego) {
        this.freightNonNego = freightNonNego;
    }

    public String getUnFreightNonNego() {
        return unFreightNonNego;
    }

    public void setUnFreightNonNego(String unFreightNonNego) {
        this.unFreightNonNego = unFreightNonNego;
    }

    public String getLatestBolId() {
        return latestBolId;
    }

    public void setLatestBolId(String latestBolId) {
        this.latestBolId = latestBolId;
    }

    public String getDoorOfDestination() {
        return doorOfDestination;
    }

    public void setDoorOfDestination(String doorOfDestination) {
        this.doorOfDestination = doorOfDestination;
    }

    public String getDoorOfOrigin() {
        return doorOfOrigin;
    }

    public void setDoorOfOrigin(String doorOfOrigin) {
        this.doorOfOrigin = doorOfOrigin;
    }

    public String[] getPrintCheck() {
        return printCheck;
    }

    public void setPrintCheck(String[] printCheck) {
        this.printCheck = printCheck;
    }

    public String getConturyOfOrigin() {
        return conturyOfOrigin;
    }

    public void setConturyOfOrigin(String conturyOfOrigin) {
        this.conturyOfOrigin = conturyOfOrigin;
    }

    public String getMasterForFreighted() {
        return masterForFreighted;
    }

    public void setMasterForFreighted(String masterForFreighted) {
        this.masterForFreighted = masterForFreighted;
    }

    public String getMasterForUnFreighted() {
        return masterForUnFreighted;
    }

    public void setMasterForUnFreighted(String masterForUnFreighted) {
        this.masterForUnFreighted = masterForUnFreighted;
    }

    public String getOriginPrePrintedForFreighted() {
        return originPrePrintedForFreighted;
    }

    public void setOriginPrePrintedForFreighted(String originPrePrintedForFreighted) {
        this.originPrePrintedForFreighted = originPrePrintedForFreighted;
    }

    public String getOriginPrePrintedForUnFreighted() {
        return originPrePrintedForUnFreighted;
    }

    public void setOriginPrePrintedForUnFreighted(
            String originPrePrintedForUnFreighted) {
        this.originPrePrintedForUnFreighted = originPrePrintedForUnFreighted;
    }

    public String getIndex() {
        return index;
    }

    public void setIndex(String index) {
        this.index = index;
    }

    public String getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(String lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getMarksNo() {
        return null != marksNo ? marksNo.toUpperCase() : "";
    }

    public void setMarksNo(String marksNo) {
        this.marksNo = marksNo;
    }

    public String getSealNo() {
        return null != sealNo ? sealNo.toUpperCase() : "";
    }

    public void setSealNo(String sealNo) {
        this.sealNo = sealNo;
    }

    public String getSizeLegend() {
        return sizeLegend;
    }

    public void setSizeLegend(String sizeLegend) {
        this.sizeLegend = sizeLegend;
    }

    public String getTrailerNo() {
        return null != trailerNo ? trailerNo.toUpperCase() : "";
    }

    public void setTrailerNo(String trailerNo) {
        this.trailerNo = trailerNo;
    }

    public String getTrialCheckbox() {
        return trialCheckbox;
    }

    public void setTrialCheckbox(String trialCheckbox) {
        this.trialCheckbox = trialCheckbox;
    }

    public String getTxtItemcreatedon1() {
        return txtItemcreatedon1;
    }

    public void setTxtItemcreatedon1(String txtItemcreatedon1) {
        this.txtItemcreatedon1 = txtItemcreatedon1;
    }

    public String[] getAccount() {
        return account;
    }

    public void setAccount(String[] account) {
        this.account = account;
    }

    public String getAltAgent() {
        return altAgent;
    }

    public void setAltAgent(String altAgent) {
        this.altAgent = altAgent;
    }

    public String[] getAmount() {
        return amount;
    }

    public void setAmount(String[] amount) {
        this.amount = amount;
    }

    public String getBillThirdParty() {
        return billThirdParty;
    }

    public void setBillThirdParty(String billThirdParty) {
        this.billThirdParty = billThirdParty;
    }

    public String[] getBillTo() {
        return billTo;
    }

    public void setBillTo(String[] billTo) {
        this.billTo = billTo;
    }

    public String getBillTrePty() {
        return billTrePty;
    }

    public void setBillTrePty(String billTrePty) {
        this.billTrePty = billTrePty;
    }

    public String[] getCharge() {
        return charge;
    }

    public void setCharge(String[] charge) {
        this.charge = charge;
    }

    public String getChargesCheckAll() {
        return chargesCheckAll;
    }

    public void setChargesCheckAll(String chargesCheckAll) {
        this.chargesCheckAll = chargesCheckAll;
    }

    public String[] getCurrency() {
        return currency;
    }

    public void setCurrency(String[] currency) {
        this.currency = currency;
    }

    public String getForwarderNo() {
        return forwarderNo;
    }

    public void setForwarderNo(String forwarderNo) {
        this.forwarderNo = forwarderNo;
    }

    public String getIndex1() {
        return index1;
    }

    public void setIndex1(String index1) {
        this.index1 = index1;
    }

    public String getIssuingTml() {
        return issuingTml;
    }

    public void setIssuingTml(String issuingTml) {
        this.issuingTml = issuingTml;
    }

    public String[] getPcollect() {
        return pcollect;
    }

    public void setPcollect(String[] pcollect) {
        this.pcollect = pcollect;
    }

    public String getPortNo() {
        return portNo;
    }

    public void setPortNo(String portNo) {
        this.portNo = portNo;
    }

    public String[] getPprepaid() {
        return pprepaid;
    }

    public void setPprepaid(String[] pprepaid) {
        this.pprepaid = pprepaid;
    }

    public String[] getPrintBl() {
        return printBl;
    }

    public void setPrintBl(String[] printBl) {
        this.printBl = printBl;
    }

    public String getRateByAgent() {
        return rateByAgent;
    }

    public void setRateByAgent(String rateByAgent) {
        this.rateByAgent = rateByAgent;
    }

    public String getReadyToPostCheck() {
        return readyToPostCheck;
    }

    public void setReadyToPostCheck(String readyToPostCheck) {
        this.readyToPostCheck = readyToPostCheck;
    }

    public String getReadyToPostCostCheck() {
        return readyToPostCostCheck;
    }

    public void setReadyToPostCostCheck(String readyToPostCostCheck) {
        this.readyToPostCostCheck = readyToPostCostCheck;
    }

    public String getReadyToPostForCost() {
        return readyToPostForCost;
    }

    public void setReadyToPostForCost(String readyToPostForCost) {
        this.readyToPostForCost = readyToPostForCost;
    }

    public String getShipperNo() {
        return shipperNo;
    }

    public void setShipperNo(String shipperNo) {
        this.shipperNo = shipperNo;
    }

    public String getSsNo() {
        return ssNo;
    }

    public void setSsNo(String ssNo) {
        this.ssNo = ssNo;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

    public String getTotalCosts() {
        return totalCosts;
    }

    public void setTotalCosts(String totalCosts) {
        this.totalCosts = totalCosts;
    }

    public String getTxtItemcreatedon() {
        return txtItemcreatedon;
    }

    public void setTxtItemcreatedon(String txtItemcreatedon) {
        this.txtItemcreatedon = txtItemcreatedon;
    }

    public String getCostCode() {
        return costCode;
    }

    public void setCostCode(String costCode) {
        this.costCode = costCode;
    }

    public String getLineMove() {
        return lineMove;
    }

    public void setLineMove(String lineMove) {
        this.lineMove = lineMove;
    }

    public String getCommodityCode() {
        return commodityCode;
    }

    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode;
    }

    public String getCommodityDesc() {
        return commodityDesc;
    }

    public void setCommodityDesc(String commodityDesc) {
        this.commodityDesc = commodityDesc;
    }

    public String getSelectedTab() {
        return selectedTab;
    }

    public void setSelectedTab(String selectedTab) {
        this.selectedTab = selectedTab;
    }

    public String getRoutedAgentCheck() {
        return routedAgentCheck;
    }

    public void setRoutedAgentCheck(String routedAgentCheck) {
        this.routedAgentCheck = routedAgentCheck;
    }

    public String getEta() {
        return eta;
    }

    public void setEta(String eta) {
        this.eta = eta;
    }

    public String getNoOfPackages() {
        return noOfPackages;
    }

    public void setNoOfPackages(String noOfPackages) {
        this.noOfPackages = noOfPackages;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getTotalContainers() {
        return totalContainers;
    }

    public void setTotalContainers(String totalContainers) {
        this.totalContainers = totalContainers;
    }

    public String getBillThirdPartyName() {
        return billThirdPartyName;
    }

    public void setBillThirdPartyName(String billThirdPartyName) {
        this.billThirdPartyName = billThirdPartyName;
    }

    public String getAutoDeductFFCom() {
        return autoDeductFFCom;
    }

    public void setAutoDeductFFCom(String autoDeductFFCom) {
        this.autoDeductFFCom = autoDeductFFCom;
    }

    public String getChargeCode() {
        return chargeCode;
    }

    public void setChargeCode(String chargeCode) {
        this.chargeCode = chargeCode;
    }

    public String getChargeCodeDesc() {
        return chargeCodeDesc;
    }

    public void setChargeCodeDesc(String chargeCodeDesc) {
        this.chargeCodeDesc = chargeCodeDesc;
    }

    public String getChargeAmount() {
        return chargeAmount;
    }

    public void setChargeAmount(String chargeAmount) {
        this.chargeAmount = chargeAmount;
    }

    public String getChargeBillTo() {
        return chargeBillTo;
    }

    public void setChargeBillTo(String chargeBillTo) {
        this.chargeBillTo = chargeBillTo;
    }

    public String getChargePrintBl() {
        return chargePrintBl;
    }

    public void setChargePrintBl(String chargePrintBl) {
        this.chargePrintBl = chargePrintBl;
    }

    public String getChargeCurrency() {
        return chargeCurrency;
    }

    public void setChargeCurrency(String chargeCurrency) {
        this.chargeCurrency = chargeCurrency;
    }

    public String getChargeId() {
        return chargeId;
    }

    public void setChargeId(String chargeId) {
        this.chargeId = chargeId;
    }

    public String getChargesRemarks() {
        return chargesRemarks;
    }

    public void setChargesRemarks(String chargesRemarks) {
        this.chargesRemarks = chargesRemarks;
    }

    public String getAdjustmentChargesRemarks() {
        return adjustmentChargesRemarks;
    }

    public void setAdjustmentChargesRemarks(String adjustmentChargesRemarks) {
        this.adjustmentChargesRemarks = adjustmentChargesRemarks;
    }

    public boolean isAdjustmentToAllContainer() {
        return adjustmentToAllContainer;
    }

    public void setAdjustmentToAllContainer(boolean adjustmentToAllContainer) {
        this.adjustmentToAllContainer = adjustmentToAllContainer;
    }

    public String getChargeFlag() {
        return chargeFlag;
    }

    public void setChargeFlag(String chargeFlag) {
        this.chargeFlag = chargeFlag;
    }

    public String getCostCodeDesc() {
        return costCodeDesc;
    }

    public void setCostCodeDesc(String costCodeDesc) {
        this.costCodeDesc = costCodeDesc;
    }

    public String getAccountNo() {
        return accountNo;
    }

    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    public String getCostAmount() {
        return costAmount;
    }

    public void setCostAmount(String costAmount) {
        this.costAmount = costAmount;
    }

    public String getCostCurrency() {
        return costCurrency;
    }

    public void setCostCurrency(String costCurrency) {
        this.costCurrency = costCurrency;
    }

    public String getDatePaid() {
        return datePaid;
    }

    public void setDatePaid(String datePaid) {
        this.datePaid = datePaid;
    }

    public String getCostComments() {
        return costComments;
    }

    public void setCostComments(String costComments) {
        this.costComments = costComments;
    }

    public String getChequeNumber() {
        return chequeNumber;
    }

    public void setChequeNumber(String chequeNumber) {
        this.chequeNumber = chequeNumber;
    }

    public String getCostCodeId() {
        return costCodeId;
    }

    public void setCostCodeId(String costCodeId) {
        this.costCodeId = costCodeId;
    }

    public String getBillToCode() {
        return billToCode;
    }

    public void setBillToCode(String billToCode) {
        this.billToCode = billToCode;
    }

    public String getConfirmOnBoard() {
        return confirmOnBoard;
    }

    public void setConfirmOnBoard(String confirmOnBoard) {
        this.confirmOnBoard = confirmOnBoard;
    }

    public String getVerifyEta() {
        return verifyEta;
    }

    public void setVerifyEta(String verifyEta) {
        this.verifyEta = verifyEta;
    }

    public String getContainerComments() {
        return null != containerComments ? containerComments.toUpperCase() : "";
    }

    public void setContainerComments(String containerComments) {
        this.containerComments = null != containerComments ? containerComments.toUpperCase() : "";
    }

    public String getTempContainerComments() {
        return null != tempContainerComments ? tempContainerComments.toUpperCase() : "";
    }

    public void setTempContainerComments(String tempContainerComments) {
        this.tempContainerComments = null != tempContainerComments ? tempContainerComments.toUpperCase() : "";
    }

    public String getAdminCost() {
        return adminCost;
    }

    public void setAdminCost(String adminCost) {
        this.adminCost = adminCost;
    }

    public String getDifferenceOfCostAndCharges() {
        return differenceOfCostAndCharges;
    }

    public void setDifferenceOfCostAndCharges(String differenceOfCostAndCharges) {
        this.differenceOfCostAndCharges = differenceOfCostAndCharges;
    }

    public String getTempFFCostCOde() {
        return tempFFCostCOde;
    }

    public void setTempFFCostCOde(String tempFFCostCOde) {
        this.tempFFCostCOde = tempFFCostCOde;
    }

    public String getTempFAECostCOde() {
        return tempFAECostCOde;
    }

    public void setTempFAECostCOde(String tempFAECostCOde) {
        this.tempFAECostCOde = tempFAECostCOde;
    }

    public String getConfOnBoardComments() {
        return null != confOnBoardComments ? confOnBoardComments.toUpperCase() : "";
    }

    public void setConfOnBoardComments(String confOnBoardComments) {
        this.confOnBoardComments = null != confOnBoardComments ? confOnBoardComments.toUpperCase() : "";
    }

    public String getNewMasterBL() {
        return null != newMasterBL ? newMasterBL.toUpperCase() : "'";
    }

    public void setNewMasterBL(String newMasterBL) {
        this.newMasterBL = null != newMasterBL ? newMasterBL.toUpperCase() : "'";
    }

    public String getAdjustmentAmount() {
        return adjustmentAmount;
    }

    public void setAdjustmentAmount(String adjustmentAmount) {
        this.adjustmentAmount = adjustmentAmount;
    }

    public String getOldAmount() {
        return oldAmount;
    }

    public void setOldAmount(String oldAmount) {
        this.oldAmount = oldAmount;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getRollUpAmount() {
        return rollUpAmount;
    }

    public void setRollUpAmount(String rollUpAmount) {
        this.rollUpAmount = rollUpAmount;
    }

    public String getNonNegotiable() {
        return nonNegotiable;
    }

    public void setNonNegotiable(String nonNegotiable) {
        this.nonNegotiable = nonNegotiable;
    }

    public String getPreAlert() {
        return preAlert;
    }

    public void setPreAlert(String preAlert) {
        this.preAlert = preAlert;
    }

    public String getProof() {
        return proof;
    }

    public void setProof(String proof) {
        this.proof = proof;
    }

    public String getImportAMSHosueBlNumber() {
        return null != importAMSHosueBlNumber ? importAMSHosueBlNumber.toUpperCase() : "";
    }

    public void setImportAMSHosueBlNumber(String importAMSHosueBlNumber) {
        this.importAMSHosueBlNumber = null != importAMSHosueBlNumber ? importAMSHosueBlNumber.toUpperCase() : "";
    }

    public String[] getAdjustment() {
        return adjustment;
    }

    public void setAdjustment(String[] adjustment) {
        this.adjustment = adjustment;
    }

    public String getImportRelease() {
        return importRelease;
    }

    public void setImportRelease(String importRelease) {
        this.importRelease = importRelease;
    }

    public String getImportReleaseComments() {
        return null != importReleaseComments ? importReleaseComments.toUpperCase() : "";
    }

    public void setImportReleaseComments(String importReleaseComments) {
        this.importReleaseComments = null != importReleaseComments ? importReleaseComments.toUpperCase() : "";
    }

    public String getImportVerifiedEta() {
        return importVerifiedEta;
    }

    public void setImportVerifiedEta(String importVerifiedEta) {
        this.importVerifiedEta = importVerifiedEta;
    }

    public String getInbondDate() {
        return inbondDate;
    }

    public void setInbondDate(String inbondDate) {
        this.inbondDate = inbondDate;
    }

    public String getInbondNumber() {
        return null != inbondNumber ? inbondNumber.toUpperCase() : "";
    }

    public void setInbondNumber(String inbondNumber) {
        this.inbondNumber = null != inbondNumber ? inbondNumber.toUpperCase() : "";
    }

    public String getInbondPort() {
        return inbondPort;
    }

    public void setInbondPort(String inbondPort) {
        this.inbondPort = inbondPort;
    }

    public String getDoorOriginAsPlor() {
        return doorOriginAsPlor;
    }

    public void setDoorOriginAsPlor(String doorOriginAsPlor) {
        this.doorOriginAsPlor = doorOriginAsPlor;
    }

    public String getDoorDestinationAsFinalDeliveryToHouse() {
        return doorDestinationAsFinalDeliveryToHouse;
    }

    public void setDoorDestinationAsFinalDeliveryToHouse(String doorDestinationAsFinalDeliveryToHouse) {
        this.doorDestinationAsFinalDeliveryToHouse = doorDestinationAsFinalDeliveryToHouse;
    }

    public String getDoorDestinationAsFinalDeliveryToMaster() {
        return doorDestinationAsFinalDeliveryToMaster;
    }

    public void setDoorDestinationAsFinalDeliveryToMaster(String doorDestinationAsFinalDeliveryToMaster) {
        this.doorDestinationAsFinalDeliveryToMaster = doorDestinationAsFinalDeliveryToMaster;
    }

    public String getCollectThirdParty() {
        return collectThirdParty;
    }

    public void setCollectThirdParty(String collectThirdParty) {
        this.collectThirdParty = collectThirdParty;
    }

    public String getHouseShipperCheck() {
        return houseShipperCheck;
    }

    public void setHouseShipperCheck(String houseShipperCheck) {
        this.houseShipperCheck = houseShipperCheck;
    }

    public String getPrintAlternatePort() {
        return printAlternatePort;
    }

    public String getAlternatePort() {
        return null != alternatePort ? alternatePort.toUpperCase() : "";
    }

    public void setAlternatePort(String alternatePort) {
        this.alternatePort = null != alternatePort ? alternatePort.toUpperCase() : "";
    }

    public void setPrintAlternatePort(String printAlternatePort) {
        this.printAlternatePort = printAlternatePort;
    }

    public String getEdiConsigneeCheck() {
        return ediConsigneeCheck;
    }

    public void setEdiConsigneeCheck(String ediConsigneeCheck) {
        this.ediConsigneeCheck = ediConsigneeCheck;
    }

    public String getEdiNotifyPartyCheck() {
        return ediNotifyPartyCheck;
    }

    public void setEdiNotifyPartyCheck(String ediNotifyPartyCheck) {
        this.ediNotifyPartyCheck = ediNotifyPartyCheck;
    }

    public String getEdiShipperCheck() {
        return ediShipperCheck;
    }

    public void setEdiShipperCheck(String ediShipperCheck) {
        this.ediShipperCheck = ediShipperCheck;
    }

    public String getAesStatus() {
        return aesStatus;
    }

    public void setAesStatus(String aesStatus) {
        this.aesStatus = aesStatus;
    }

    public String getTrnref() {
        return trnref;
    }

    public void setTrnref(String trnref) {
        this.trnref = trnref;
    }

    public String getTrimTrailingZerosForQty() {
        return trimTrailingZerosForQty;
    }

    public void setTrimTrailingZerosForQty(String trimTrailingZerosForQty) {
        this.trimTrailingZerosForQty = trimTrailingZerosForQty;
    }

    public String getFclSsblGoCollect() {
        return fclSsblGoCollect;
    }

    public void setFclSsblGoCollect(String fclSsblGoCollect) {
        this.fclSsblGoCollect = fclSsblGoCollect;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public String getOldComment() {
        return oldComment;
    }

    public void setOldComment(String oldComment) {
        this.oldComment = oldComment;
    }

    public String getOldCost() {
        return oldCost;
    }

    public void setOldCost(String oldCost) {
        this.oldCost = oldCost;
    }

    public String getOldCostCode() {
        return oldCostCode;
    }

    public void setOldCostCode(String oldCostCode) {
        this.oldCostCode = oldCostCode;
    }

    public String getOldCostCodeDesc() {
        return oldCostCodeDesc;
    }

    public void setOldCostCodeDesc(String oldCostCodeDesc) {
        this.oldCostCodeDesc = oldCostCodeDesc;
    }

    public String getOldVendor() {
        return oldVendor;
    }

    public void setOldVendor(String oldVendor) {
        this.oldVendor = oldVendor;
    }

    public String getOldVendorName() {
        return oldVendorName;
    }

    public void setOldVendorName(String oldVendorName) {
        this.oldVendorName = oldVendorName;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getNvoCheckBox() {
        return nvoCheckBox;
    }

    public void setNvoCheckBox(String nvoCheckBox) {
        this.nvoCheckBox = nvoCheckBox;
    }

    public String getVendorCheckBox() {
        return vendorCheckBox;
    }

    public void setVendorCheckBox(String vendorCheckBox) {
        this.vendorCheckBox = vendorCheckBox;
    }

    public String getVendorName() {
        return vendorName;
    }

    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    public String getVendorNumber() {
        return vendorNumber;
    }

    public void setVendorNumber(String vendorNumber) {
        this.vendorNumber = vendorNumber;
    }

    public String getTransferCost() {
        return transferCost;
    }

    public void setTransferCost(String transferCost) {
        this.transferCost = transferCost;
    }

    public String getBundleIntoOfr() {
        return bundleIntoOfr;
    }

    public void setBundleIntoOfr(String bundleIntoOfr) {
        this.bundleIntoOfr = bundleIntoOfr;
    }

    public String getEditHouseShipperCheck() {
        return editHouseShipperCheck;
    }

    public void setEditHouseShipperCheck(String editHouseShipperCheck) {
        this.editHouseShipperCheck = editHouseShipperCheck;
    }

    public String getInsurance() {
        return insurance;
    }

    public void setInsurance(String insurance) {
        this.insurance = insurance;
    }

    public String getInsuranceRate() {
        return insuranceRate;
    }

    public void setInsuranceRate(String insuranceRate) {
        this.insuranceRate = insuranceRate;
    }

    public String getCostOfGoods() {
        return costOfGoods;
    }

    public void setCostOfGoods(String costOfGoods) {
        this.costOfGoods = costOfGoods;
    }

    public String getDirectConsignment() {
        return directConsignment;
    }

    public void setDirectConsignment(String directConsignment) {
        this.directConsignment = directConsignment;
    }

    public String getEditHouseConsigneeCheck() {
        return editHouseConsigneeCheck;
    }

    public void setEditHouseConsigneeCheck(String editHouseConsigneeCheck) {
        this.editHouseConsigneeCheck = editHouseConsigneeCheck;
    }

    public String getEditHouseNotifyCheck() {
        return editHouseNotifyCheck;
    }

    public void setEditHouseNotifyCheck(String editHouseNotifyCheck) {
        this.editHouseNotifyCheck = editHouseNotifyCheck;
    }

    public String getOmitTermAndPort() {
        return omitTermAndPort;
    }

    public void setOmitTermAndPort(String omitTermAndPort) {
        this.omitTermAndPort = omitTermAndPort;
    }

    public String getHblFDOverride() {
        return hblFDOverride;
    }

    public void setHblFDOverride(String hblFDOverride) {
        this.hblFDOverride = hblFDOverride;
    }

    public String getHblPODOverride() {
        return hblPODOverride;
    }

    public void setHblPODOverride(String hblPODOverride) {
        this.hblPODOverride = hblPODOverride;
    }

    public String getHblPOLOverride() {
        return hblPOLOverride;
    }

    public void setHblPOLOverride(String hblPOLOverride) {
        this.hblPOLOverride = hblPOLOverride;
    }

    public String getHblFD() {
        return hblFD;
    }

    public void setHblFD(String hblFD) {
        this.hblFD = hblFD;
    }

    public String getHblPOD() {
        return hblPOD;
    }

    public void setHblPOD(String hblPOD) {
        this.hblPOD = hblPOD;
    }

    public String getHblPOL() {
        return hblPOL;
    }

    public void setHblPOL(String hblPOL) {
        this.hblPOL = hblPOL;
    }

    public String getInternalRemark() {
        return internalRemark;
    }

    public void setInternalRemark(String internalRemark) {
        this.internalRemark = internalRemark;
    }

    public String getServiceContractNo() {
        return serviceContractNo;
    }

    public void setServiceContractNo(String serviceContractNo) {
        this.serviceContractNo = serviceContractNo;
    }

    public String getTrailerNoOld() {
        return trailerNoOld;
    }

    public void setTrailerNoOld(String trailerNoOld) {
        this.trailerNoOld = trailerNoOld;
    }

    public String getEditAgentNameCheck() {
        return editAgentNameCheck;
    }

    public void setEditAgentNameCheck(String editAgentNameCheck) {
        this.editAgentNameCheck = editAgentNameCheck;
    }

    public String getReplaceArrival() {
        return replaceArrival;
    }

    public void setReplaceArrival(String replaceArrival) {
        this.replaceArrival = replaceArrival;
    }

    public String getCertifiedTrueCopy() {
        return certifiedTrueCopy;
    }

    public void setCertifiedTrueCopy(String certifiedTrueCopy) {
        this.certifiedTrueCopy = certifiedTrueCopy;
    }

    public String getDocCutOff() {
        return docCutOff;
    }

    public void setDocCutOff(String docCutOff) {
        this.docCutOff = docCutOff;
    }

    public String getPortCutOff() {
        return portCutOff;
    }

    public void setPortCutOff(String portCutOff) {
        this.portCutOff = portCutOff;
    }

    public String getEarlierPickUpDate() {
        return earlierPickUpDate;
    }

    public void setEarlierPickUpDate(String earlierPickUpDate) {
        this.earlierPickUpDate = earlierPickUpDate;
    }

    public String getEtaFd() {
        return etaFd;
    }

    public void setEtaFd(String etaFd) {
        this.etaFd = etaFd;
    }

    public String getVesselNameCheck() {
        return vesselNameCheck;
    }

    public void setVesselNameCheck(String vesselNameCheck) {
        this.vesselNameCheck = vesselNameCheck;
    }

    public String getManualVesselName() {
        return manualVesselName.toUpperCase();
    }

    public void setManualVesselName(String manualVesselName) {
        this.manualVesselName = manualVesselName.toUpperCase();
    }

    public String getDoorOriginAsPlorHouse() {
        return null != doorOriginAsPlorHouse ? doorOriginAsPlorHouse : "Yes";
    }

    public void setDoorOriginAsPlorHouse(String doorOriginAsPlorHouse) {
        this.doorOriginAsPlorHouse = doorOriginAsPlorHouse;
    }

    public String getDockReceipt() {
        return null != dockReceipt ? dockReceipt : "No";
    }

    public void setDockReceipt(String dockReceipt) {
        this.dockReceipt = null != dockReceipt ? dockReceipt : "No";
    }

    public String getTrailerNoId() {
        return trailerNoId;
    }

    public void setTrailerNoId(String trailerNoId) {
        this.trailerNoId = trailerNoId;
    }

    public String getAlternateNoOfPackages() {
        return alternateNoOfPackages;
    }

    public void setAlternateNoOfPackages(String alternateNoOfPackages) {
        this.alternateNoOfPackages = alternateNoOfPackages;
    }

    public String getManuallyAddedFlag() {
        return manuallyAddedFlag;
    }

    public void setManuallyAddedFlag(String manuallyAddedFlag) {
        this.manuallyAddedFlag = manuallyAddedFlag;
    }

    public String getResendCostToBlue() {
        return null != resendCostToBlue ? resendCostToBlue : "No";
    }

    public void setResendCostToBlue(String resendCostToBlue) {
        this.resendCostToBlue = resendCostToBlue;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getFreightInvoiceContacts() {
        return freightInvoiceContacts;
    }

    public void setFreightInvoiceContacts(String freightInvoiceContacts) {
        this.freightInvoiceContacts = freightInvoiceContacts;
    }

}
