package com.gp.cong.logisoft.lcl.kn.bc;

import com.gp.cong.logisoft.kn.beans.Booking;
import com.gp.cong.logisoft.kn.beans.BookingHaz;
import com.gp.cong.struts.LoadLogisoftProperties;
import java.util.Map;

/**
 *
 * @author Rajesh
 */
public class QueryUtil {

    private static String logiwareDb = PropertyUtils.getProperty("logiware_db_name");
    private static String senderMappingDesc = "Sender mapping";

    public static String createBookingNo() {
        return "{? = CALL CreateWebToolsBkgNumber()}";
    }

    public static String updateBkgNo(Long bkgDetailId, String bkgNo) {
        return "update kn_bkg_details b set b.bkg_number = lpad('"
                + bkgNo + "',6,0) where b.id = " + bkgDetailId;
    }

    public static StringBuilder saveBookingHaz(Map<String, String> valueMap, BookingHaz bkg) {
        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append(" insert into ").append("").append(".booking_hazardous (");
        queryBuilder.append(" booking_id,");
        queryBuilder.append(" un_number,");
        queryBuilder.append(" proper_shipper_name,");
        queryBuilder.append(" haz_class,");
        queryBuilder.append(" flash_point,");
        queryBuilder.append(" flash_point_uom,");
        queryBuilder.append(" packing_group");
        queryBuilder.append(" ) values (");
        queryBuilder.append("'").append(valueMap.get("bkgNo")).append("',");
        queryBuilder.append("'").append(bkg.getUnNumber()).append("',");
        queryBuilder.append("'").append(bkg.getProperShippingName()).append("',");
        queryBuilder.append("'").append(bkg.getHazClass()).append("',");
        queryBuilder.append("'").append(bkg.getFlashPoint()).append("',");
        queryBuilder.append("'").append(bkg.getFlashPointFlag()).append("',");
        queryBuilder.append("'").append(bkg.getPackageGroup()).append("')");
        return queryBuilder;
    }

    public static StringBuilder saveBooking(Booking bkg) throws IllegalArgumentException {
        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append(" insert into ").append("bkgbookings (");
        queryBuilder.append(" Orgtml,Drcnum,");
        queryBuilder.append(" Bkgtml,");
        queryBuilder.append(" Dstprt,");
        queryBuilder.append(" Voynum,");
        queryBuilder.append(" Billng,");
        queryBuilder.append(" Shpnam,");
        queryBuilder.append(" Shpcar,");
        queryBuilder.append(" Shpad1,");
        queryBuilder.append(" Shpad2,");
        queryBuilder.append(" Shpcty,");
        queryBuilder.append(" Shpsta,");
        queryBuilder.append(" Shpcnt,");
        queryBuilder.append(" Shppos,");
        queryBuilder.append(" Shpphn,");
        queryBuilder.append(" Shpfax,");
        queryBuilder.append(" Fwdnam,");
        queryBuilder.append(" Fwdcar,");
        queryBuilder.append(" Fwdad1,");
        queryBuilder.append(" Fwdad2,");
        queryBuilder.append(" Fwdcty,");
        queryBuilder.append(" Fwdsta,");
        queryBuilder.append(" Fwdcnt,");
        queryBuilder.append(" Fwdpos,");
        queryBuilder.append(" Fwdphn,");
        queryBuilder.append(" Fwdfax,");
        queryBuilder.append(" Connam,");
        queryBuilder.append(" Concar,");
        queryBuilder.append(" Conad1,");
        queryBuilder.append(" Conad2,");
        queryBuilder.append(" Concty,");
        queryBuilder.append(" Consta,");
        queryBuilder.append(" Concnt,");
        queryBuilder.append(" Conpos,");
        queryBuilder.append(" Conphn,");
        queryBuilder.append(" Confax,");
        queryBuilder.append(" Notnam,");
        queryBuilder.append(" Notcar,");
        queryBuilder.append(" Notad1,");
        queryBuilder.append(" Notad2,");
        queryBuilder.append(" Notcty,");
        queryBuilder.append(" Notsta,");
        queryBuilder.append(" Notcnt,");
        queryBuilder.append(" Notzip,");
        queryBuilder.append(" Notphn,");
        queryBuilder.append(" Notfax,");
        queryBuilder.append(" Pcs1,");
        queryBuilder.append(" Pcs2,");
        queryBuilder.append(" Pcs3,");
        queryBuilder.append(" Pcs4,");
        queryBuilder.append(" Pct1,");
        queryBuilder.append(" Pct2,");
        queryBuilder.append(" Pct3,");
        queryBuilder.append(" Pct4,");
        queryBuilder.append(" Wgt1,");
        queryBuilder.append(" Wgt2,");
        queryBuilder.append(" Wgt3,");
        queryBuilder.append(" Wgt4,");
        queryBuilder.append(" Wtp1,");
        queryBuilder.append(" Wtp2,");
        queryBuilder.append(" Wtp3,");
        queryBuilder.append(" Wtp4,");
        queryBuilder.append(" Msr1,");
        queryBuilder.append(" Msr2,");
        queryBuilder.append(" Msr3,");
        queryBuilder.append(" Msr4,");
        queryBuilder.append(" Mtp1,");
        queryBuilder.append(" Mtp2,");
        queryBuilder.append(" Mtp3,");
        queryBuilder.append(" Mtp4,");
        queryBuilder.append(" Cm1,");
        queryBuilder.append(" Cm2,");
        queryBuilder.append(" Cm3,");
        queryBuilder.append(" Cm4,");
        queryBuilder.append(" Hazcrg,");
        queryBuilder.append(" Pickup,");
        queryBuilder.append(" Bonded,");
        queryBuilder.append(" Licnsd,");
        queryBuilder.append(" Rtngds,");
        queryBuilder.append(" Elcexd,");
        queryBuilder.append(" xtnnm1,");
        queryBuilder.append(" xtnnm2,");
        queryBuilder.append(" Pshpnm,");
        queryBuilder.append(" Tchmnm,");
        queryBuilder.append(" Hzclas,");
        queryBuilder.append(" Unnumb,");
        queryBuilder.append(" pkggrp,");
        queryBuilder.append(" Flshpt,");
        queryBuilder.append(" Flshtm,");
        queryBuilder.append(" Outpkg,");
        queryBuilder.append(" Innpkg,");
        queryBuilder.append(" othpk1,");
        queryBuilder.append(" othpk2,");
        queryBuilder.append(" Lmtqty,");
        queryBuilder.append(" Marplt,");
        queryBuilder.append(" Rptqty,");
        queryBuilder.append(" Inhhaz,");
        queryBuilder.append(" Inhzon,");
        queryBuilder.append(" Emgcon,");
        queryBuilder.append(" attch1,");
        queryBuilder.append(" attch2,");
        queryBuilder.append(" attch3,");
        queryBuilder.append(" Logip,");
        queryBuilder.append(" Logses,");
        queryBuilder.append(" Logid,");
        queryBuilder.append(" Logcmp,");
        queryBuilder.append(" Logtme,");
        queryBuilder.append(" Cmpnum,");
        queryBuilder.append(" Contact,");
        queryBuilder.append(" Pucomp,");
        queryBuilder.append(" puadr1,");
        queryBuilder.append(" Pucity,");
        queryBuilder.append(" Pustat,");
        queryBuilder.append(" Puzipc,");
        queryBuilder.append(" Pucnam,");
        queryBuilder.append(" Puphon,");
        queryBuilder.append(" Pufax,");
        queryBuilder.append(" Puhrs,");
        queryBuilder.append(" Pudate,");
        queryBuilder.append(" Pucmmt,");
        queryBuilder.append(" Ecquot,");
        queryBuilder.append(" Ecqtnm,");
        queryBuilder.append(" cmmnt1,");
        queryBuilder.append(" cmmnt2,");
        queryBuilder.append(" cmmnt3,");
        queryBuilder.append(" cmmnt4,");
        queryBuilder.append(" cmmnt5,");
        queryBuilder.append(" Cmptyp,");
        queryBuilder.append(" Cnteml,");
        queryBuilder.append(" Ovdims,");
        queryBuilder.append(" Ecidte,");
        queryBuilder.append(" Poo,");
        queryBuilder.append(" Pol,");
        queryBuilder.append(" Pod,");
        queryBuilder.append(" Fd,");
        queryBuilder.append(" Gr,");
        queryBuilder.append(" Frtref,");
        queryBuilder.append(" Shpref,");
        queryBuilder.append(" Conref,");
        queryBuilder.append(" upddte,");
        queryBuilder.append(" updtim");
        queryBuilder.append(") values (");
        queryBuilder.append("'").append(bkg.getOriginTerminal()).append("',");
        if (null == bkg.getOriginTerminal() || "".equals(bkg.getOriginTerminal().trim())) {
            throw new IllegalArgumentException("Orgin terminal is unknown");
        }
        queryBuilder.append("'").append(bkg.getDockReceiptNo()).append("',");
        queryBuilder.append("'").append(bkg.getBkgTerminal()).append("',");
        queryBuilder.append("'").append(bkg.getPortNo()).append("',");
        queryBuilder.append("'").append(bkg.getVoyageNumber()).append("',");
        queryBuilder.append("'").append(bkg.getBilling()).append("',");
        queryBuilder.append("'").append(bkg.getCustomerContact()).append("',");
        queryBuilder.append("'").append(bkg.getShipperCar()).append("',");
        queryBuilder.append("'").append(bkg.getShipperAddress1()).append("',");
        queryBuilder.append("'").append(bkg.getShipperAddress2()).append("',");
        queryBuilder.append("'").append(bkg.getShipperCity()).append("',");
        queryBuilder.append("'").append(bkg.getShipperState()).append("',");
        queryBuilder.append("'").append(bkg.getShipperCountry()).append("',");
        queryBuilder.append("'").append(bkg.getShipperPos()).append("',");
        queryBuilder.append("'").append(bkg.getShipperPhone()).append("',");
        queryBuilder.append("'").append(bkg.getShipperFax()).append("',");
        queryBuilder.append("'").append(bkg.getFwdName()).append("',");
        queryBuilder.append("'").append(bkg.getFwdCar()).append("',");
        queryBuilder.append("'").append(bkg.getFwdAddress1()).append("',");
        queryBuilder.append("'").append(bkg.getFwdAddress2()).append("',");
        queryBuilder.append("'").append(bkg.getFwdCity()).append("',");
        queryBuilder.append("'").append(bkg.getFwdState()).append("',");
        queryBuilder.append("'").append(bkg.getFwdCountry()).append("',");
        queryBuilder.append("'").append(bkg.getFwdPos()).append("',");
        queryBuilder.append("'").append(bkg.getFwdPhone()).append("',");
        queryBuilder.append("'").append(bkg.getFwdFax()).append("',");
        queryBuilder.append("'").append(bkg.getConName()).append("',");
        queryBuilder.append("'").append(bkg.getConCar()).append("',");
        queryBuilder.append("'").append(bkg.getConAddress1()).append("',");
        queryBuilder.append("'").append(bkg.getConAddress2()).append("',");
        queryBuilder.append("'").append(bkg.getConCity()).append("',");
        queryBuilder.append("'").append(bkg.getConState()).append("',");
        queryBuilder.append("'").append(bkg.getConCountry()).append("',");
        queryBuilder.append("'").append(bkg.getConPos()).append("',");
        queryBuilder.append("'").append(bkg.getConPhone()).append("',");
        queryBuilder.append("'").append(bkg.getConFax()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyName()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyCar()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyAddress1()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyAddress2()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyCity()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyState()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyCountry()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyzip()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyPhone()).append("',");
        queryBuilder.append("'").append(bkg.getNotifyFax()).append("',");
        queryBuilder.append("'").append(bkg.getPc1()).append("',");
        queryBuilder.append("'").append(bkg.getPc2()).append("',");
        queryBuilder.append("'").append(bkg.getPc3()).append("',");
        queryBuilder.append("'").append(bkg.getPc4()).append("',");
        queryBuilder.append("'").append(bkg.getPct1()).append("',");
        queryBuilder.append("'").append(bkg.getPct2()).append("',");
        queryBuilder.append("'").append(bkg.getPct3()).append("',");
        queryBuilder.append("'").append(bkg.getPct4()).append("',");
        queryBuilder.append("'").append(bkg.getWgt1()).append("',");
        queryBuilder.append("'").append(bkg.getWgt2()).append("',");
        queryBuilder.append("'").append(bkg.getWgt3()).append("',");
        queryBuilder.append("'").append(bkg.getWgt4()).append("',");
        queryBuilder.append("'").append(bkg.getWtp1()).append("',");
        queryBuilder.append("'").append(bkg.getWtp2()).append("',");
        queryBuilder.append("'").append(bkg.getWtp3()).append("',");
        queryBuilder.append("'").append(bkg.getWtp4()).append("',");
        queryBuilder.append("'").append(bkg.getMsr1()).append("',");
        queryBuilder.append("'").append(bkg.getMsr2()).append("',");
        queryBuilder.append("'").append(bkg.getMsr3()).append("',");
        queryBuilder.append("'").append(bkg.getMsr4()).append("',");
        queryBuilder.append("'").append(bkg.getMtp1()).append("',");
        queryBuilder.append("'").append(bkg.getMtp2()).append("',");
        queryBuilder.append("'").append(bkg.getMtp3()).append("',");
        queryBuilder.append("'").append(bkg.getMtp4()).append("',");
        queryBuilder.append("'").append(bkg.getCm1()).append("',");
        queryBuilder.append("'").append(bkg.getCm2()).append("',");
        queryBuilder.append("'").append(bkg.getCm3()).append("',");
        queryBuilder.append("'").append(bkg.getCm4()).append("',");
        queryBuilder.append("'").append(bkg.getHazFlag()).append("',");
        queryBuilder.append("'").append(bkg.getPickupFlag()).append("',");
        queryBuilder.append("'").append(bkg.getBonded()).append("',");
        queryBuilder.append("'").append(bkg.getLicnsd()).append("',");
        queryBuilder.append("'").append(bkg.getRtngds()).append("',");
        queryBuilder.append("'").append(bkg.getElcexd()).append("',");
        queryBuilder.append("'").append(bkg.getXtnnm1()).append("',");
        queryBuilder.append("'").append(bkg.getXtnnm2()).append("',");
        queryBuilder.append("'").append(bkg.getPshpnm()).append("',");
        queryBuilder.append("'").append(bkg.getTchmnm()).append("',");
        queryBuilder.append("'").append(bkg.getHazClass()).append("',");
        queryBuilder.append("'").append(bkg.getUnnumb()).append("',");
        queryBuilder.append("'").append(bkg.getPkggrp()).append("',");
        queryBuilder.append("'").append(bkg.getFlshpt()).append("',");
        queryBuilder.append("'").append(bkg.getFlshtm()).append("',");
        queryBuilder.append("'").append(bkg.getOutpkg()).append("',");
        queryBuilder.append("'").append(bkg.getInnpkg()).append("',");
        queryBuilder.append("'").append(bkg.getOthpk1()).append("',");
        queryBuilder.append("'").append(bkg.getOthpk2()).append("',");
        queryBuilder.append("'").append(bkg.getLmtqty()).append("',");
        queryBuilder.append("'").append(bkg.getMarplt()).append("',");
        queryBuilder.append("'").append(bkg.getRptqty()).append("',");
        queryBuilder.append("'").append(bkg.getInhhaz()).append("',");
        queryBuilder.append("'").append(bkg.getInhzon()).append("',");
        queryBuilder.append("'").append(bkg.getEmgcon()).append("',");
        queryBuilder.append("'").append(bkg.getAttch1()).append("',");
        queryBuilder.append("'").append(bkg.getAttch2()).append("',");
        queryBuilder.append("'").append(bkg.getAttch3()).append("',");
        queryBuilder.append("'").append(bkg.getLogip()).append("',");
        queryBuilder.append("'").append(bkg.getLogses()).append("',");
        queryBuilder.append("'").append(bkg.getLogid()).append("',");
        queryBuilder.append("'").append(bkg.getLogcmp()).append("',");
        queryBuilder.append("'").append(bkg.getLogtme()).append("',");
        queryBuilder.append("'").append(bkg.getCmpnum()).append("',");
        queryBuilder.append("'").append(bkg.getContact()).append("',");
        queryBuilder.append("'").append(bkg.getPucomp()).append("',");
        queryBuilder.append("'").append(bkg.getPuadr1()).append("',");
        queryBuilder.append("'").append(bkg.getPucity()).append("',");
        queryBuilder.append("'").append(bkg.getPustat()).append("',");
        queryBuilder.append("'").append(bkg.getPucname()).append("',");
        queryBuilder.append("'").append(bkg.getPuzipc()).append("',");
        queryBuilder.append("'").append(bkg.getPuphon()).append("',");
        queryBuilder.append("'").append(bkg.getPufax()).append("',");
        queryBuilder.append("'").append(bkg.getPuhrs()).append("',");
        queryBuilder.append("'").append(bkg.getPudate()).append("',");
        queryBuilder.append("'").append(bkg.getPucmmt()).append("',");
        queryBuilder.append("'").append(bkg.getEcquot()).append("',");
        queryBuilder.append("'").append(bkg.getEcqtnm()).append("',");
        queryBuilder.append("'").append(bkg.getCmmnt1()).append("',");
        queryBuilder.append("'").append(bkg.getCmmnt2()).append("',");
        queryBuilder.append("'").append(bkg.getCmmnt3()).append("',");
        queryBuilder.append("'").append(bkg.getCmmnt4()).append("',");
        queryBuilder.append("'").append(bkg.getCmmnt5()).append("',");
        queryBuilder.append("'").append(bkg.getCmptyp()).append("',");
        queryBuilder.append("'").append(bkg.getCnteml()).append("',");
        queryBuilder.append("'").append(bkg.getOvdims()).append("',");
        queryBuilder.append("'").append(bkg.getEcidte()).append("',");
        queryBuilder.append("'").append(bkg.getPoo()).append("',");
        queryBuilder.append("'").append(bkg.getPol()).append("',");
        queryBuilder.append("'").append(bkg.getPod()).append("',");
        queryBuilder.append("'").append(bkg.getFd()).append("',");
        queryBuilder.append("'").append(bkg.getGr()).append("',");
        queryBuilder.append("'").append(bkg.getFrtref()).append("',");
        queryBuilder.append("'").append(bkg.getShpref()).append("',");
        queryBuilder.append("'").append(bkg.getConref()).append("',");
        queryBuilder.append("'").append(bkg.getUpdatedDate()).append("',");
        queryBuilder.append("'").append(bkg.getUpdatedTime()).append("'");
        queryBuilder.append(")");
        return queryBuilder;
    }

    public static StringBuilder fetchBooking(Map<String, String> valueMap) throws Exception {
        String bluescreenDb = LoadLogisoftProperties.getProperty("elite.database.name");
        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("select ");
        queryBuilder.append(" org.ecitrm as originTerminal,");
        queryBuilder.append(" '' as dockReceiptNo,");
        queryBuilder.append(" '01' as bkgTerminal,");
        queryBuilder.append(" dest_port.prtnum as portNo,");
        queryBuilder.append(" concat(");
        queryBuilder.append(" '01',");
        queryBuilder.append(" dest_port.prtnum,");
        queryBuilder.append(" sail.voyage");
        queryBuilder.append(" ) voyageNumber,");
        queryBuilder.append(" 'C' as billing,");
        queryBuilder.append(" if(gc.field1 = 'S', bkg.customer_contact,'') as customerContact,");
        queryBuilder.append(" '' as shipperCar,");
        queryBuilder.append(" '' as shipperAddress1,");
        queryBuilder.append(" '' as shipperAddress2,");
        queryBuilder.append(" '' as shipperCity,");
        queryBuilder.append(" '' as shipperState,");
        queryBuilder.append(" '' as shipperCountry,");
        queryBuilder.append(" '' as shipperPos,");
        queryBuilder.append(" if(gc.field1 = 'S', bkg.customer_phone,'') as shipperPhone,");
        queryBuilder.append(" '' as shipperFax,");
        queryBuilder.append(" if(gc.field1 = 'F', bkg.customer_contact,'')  as fwdName,");
        queryBuilder.append(" '' as fwdCar,");
        queryBuilder.append(" '' as fwdAddress1,");
        queryBuilder.append(" '' as fwdAddress2,");
        queryBuilder.append(" '' as fwdCity,");
        queryBuilder.append(" '' as fwdState,");
        queryBuilder.append(" '' as fwdCountry,");
        queryBuilder.append(" '' as fwdPos,");
        queryBuilder.append(" if(gc.field1 = 'F', bkg.customer_phone,'') as fwdPhone,");
        queryBuilder.append(" '' as fwdFax,");
        queryBuilder.append(" if(gc.field1 = 'C', bkg.customer_contact,'') as conName,");
        queryBuilder.append(" '' as conCar,");
        queryBuilder.append(" '' as conAddress1,");
        queryBuilder.append(" '' as conAddress2,");
        queryBuilder.append(" '' as conCity,");
        queryBuilder.append(" '' as conState,");
        queryBuilder.append(" '' as conCountry,");
        queryBuilder.append(" '' as conPos,");
        queryBuilder.append(" if(gc.field1 = 'C', bkg.customer_phone,'') as conPhone,");
        queryBuilder.append(" '' as conFax,");
        queryBuilder.append(" '' as notifyName,");
        queryBuilder.append(" '' as notifyCar,");
        queryBuilder.append(" '' as notifyAddress1,");
        queryBuilder.append(" '' as notifyAddress2,");
        queryBuilder.append(" '' as notifyCity,");
        queryBuilder.append(" '' as notifyState,");
        queryBuilder.append(" '' as notifyCountry,");
        queryBuilder.append(" '' as notifyzip,");
        queryBuilder.append(" '' as notifyPhone,");
        queryBuilder.append(" '' as notifyFax,");
        queryBuilder.append(" substring_index(group_concat(cargo.pieces), ',', 1) as pc1,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.pieces) >= 2,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.pieces), ',', 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as pc2,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.pieces) >= 3,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.pieces), ',', - 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as pc3,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.pieces) >= 4,");
        queryBuilder.append(" substring_index(group_concat(cargo.pieces), ',', - 1),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as pc4,");
        queryBuilder.append(" substring_index(group_concat(cargo.package), ',', 1) as pct1,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.package) >= 2,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.package), ',', 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as pct2,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.package) >= 3,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" group_concat(cargo.package),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 2");
        queryBuilder.append(" ),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as pct3,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.package) >= 4,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" group_concat(cargo.package),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as pct4,");
        queryBuilder.append(" substring_index(group_concat(cargo.weight), ',', 1) as wgt1,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.weight) >= 2,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.weight), ',', 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as wgt2,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.weight) >= 3,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.weight), ',', - 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as wgt3,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.weight) >= 4,");
        queryBuilder.append(" substring_index(group_concat(cargo.weight), ',', - 1),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as wgt4,");
        queryBuilder.append(" substring_index(group_concat(cargo.uom), ',', 1) as wtp1,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.uom) >= 2,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.uom), ',', 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as wtp2,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.uom) >= 3,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.uom), ',', - 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as wtp3,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.uom) >= 4,");
        queryBuilder.append(" substring_index(group_concat(cargo.uom), ',', - 1),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as wtp4,");
        queryBuilder.append(" substring_index(group_concat(cargo.volume), ',', 1) as msr1,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.volume) >= 2,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.volume), ',', 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as msr2,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.volume) >= 3,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.volume), ',', - 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as msr3,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.volume) >= 4,");
        queryBuilder.append(" substring_index(group_concat(cargo.volume), ',', - 1),");
        queryBuilder.append(" 0");
        queryBuilder.append(" ) as msr4,");
        queryBuilder.append(" substring_index(group_concat(cargo.uom), ',', 1) as mtp1,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.uom) >= 2,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.uom), ',', 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as mtp2,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.uom) >= 3,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(group_concat(cargo.uom), ',', - 2),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as mtp3,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.uom) >= 4,");
        queryBuilder.append(" substring_index(group_concat(cargo.uom), ',', - 1),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as mtp4,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" group_concat(cargo.commodity),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 1");
        queryBuilder.append(" ) as cm1,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.commodity) >= 2,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" group_concat(cargo.commodity),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 2");
        queryBuilder.append(" ),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as cm2,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.commodity) >= 3,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" group_concat(cargo.commodity),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 2");
        queryBuilder.append(" ),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as cm3,");
        queryBuilder.append(" if(");
        queryBuilder.append(" count(cargo.commodity) >= 4,");
        queryBuilder.append(" substring_index(");
        queryBuilder.append(" group_concat(cargo.commodity),");
        queryBuilder.append(" ',',");
        queryBuilder.append(" - 1");
        queryBuilder.append(" ),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as cm4,");
        queryBuilder.append(" cargo.haz_flag as hazFlag,");
        queryBuilder.append(" bkg.pickup_flag as pickupFlag,");
        queryBuilder.append(" '' as bonded,");
        queryBuilder.append(" '' as licnsd,");
        queryBuilder.append(" '' as rtngds,");
        queryBuilder.append(" '' as elcexd,");
        queryBuilder.append(" '' as xtnnm1,");
        queryBuilder.append(" '' as xtnnm2,");
        queryBuilder.append(" haz.shipping_name as pshpnm,");
        queryBuilder.append(" '' as tchmnm,");
        queryBuilder.append(" haz.class as hazClass,");
        queryBuilder.append(" haz.un_number as unnumb,");
        queryBuilder.append(" haz.pack_group as pkggrp,");
        queryBuilder.append(" ifnull(haz.flash_point,0) as flshpt,");
        queryBuilder.append(" ifnull(haz.flash_point_flag,'') as flshtm,");
        queryBuilder.append(" '' as outpkg,");
        queryBuilder.append(" '' as innpkg,");
        queryBuilder.append(" '' as othpk1,");
        queryBuilder.append(" '' as othpk2,");
        queryBuilder.append(" '' as lmtqty,");
        queryBuilder.append(" '' as marplt,");
        queryBuilder.append(" '' as rptqty,");
        queryBuilder.append(" '' as inhhaz,");
        queryBuilder.append(" '' as inhzon,");
        queryBuilder.append(" '' as emgcon,");
        queryBuilder.append(" '' as attch1,");
        queryBuilder.append(" '' as attch2,");
        queryBuilder.append(" '' as attch3,");
        queryBuilder.append(" '' as logip,");
        queryBuilder.append(" '' as logses,");
        queryBuilder.append(" if(gc.field1 = 'C',con.fusrnm,ff.fusrnm) as logid,");
        queryBuilder.append(" gc.codedesc as logcmp,");
        queryBuilder.append(" date_Format(now(),'%Y-%m-%d %T') as logtme,");
        queryBuilder.append(" gc.codedesc as cmpnum,");
        queryBuilder.append(" '' as contact,");
        queryBuilder.append(" ifnull(pickup.company_name, '') as pucomp,");
        queryBuilder.append(" ifnull(pickup.address, '') as puadr1,");
        queryBuilder.append(" ifnull(pickup.city, '') as pucity,");
        queryBuilder.append(" ifnull(pickup.state, '') as pustat,");
        queryBuilder.append(" '' as pucname,");
        queryBuilder.append(" ifnull(pickup.zip, '') as puzipc,");
        queryBuilder.append(" ifnull(pickup.phone, '') as puphon,");
        queryBuilder.append(" '' as pufax,");
        queryBuilder.append(" ifnull(");
        queryBuilder.append(" cast(pickup.pickup_date as time),");
        queryBuilder.append(" ''");
        queryBuilder.append(" ) as puhrs,");
        queryBuilder.append(" ifnull(");
        queryBuilder.append(" cast(pickup.pickup_date as date),");
        queryBuilder.append(" now()");
        queryBuilder.append(" ) as pudate,");
        queryBuilder.append(" '' as pucmmt,");
        queryBuilder.append(" '' as ecquot,");
        queryBuilder.append(" '' as ecqtnm,");
        queryBuilder.append(" '' as cmmnt1,");
        queryBuilder.append(" '' as cmmnt2,");
        queryBuilder.append(" '' as cmmnt3,");
        queryBuilder.append(" '' as cmmnt4,");
        queryBuilder.append(" '' as cmmnt5,");
        queryBuilder.append(" '' as cmptyp,");
        queryBuilder.append(" bkg.customer_email as cnteml,");
        queryBuilder.append(" '' as ovdims,");
        queryBuilder.append(" '' as ecidte,");
        queryBuilder.append(" '' as poo,");
        queryBuilder.append(" '' as pol,");
        queryBuilder.append(" '' as pod,");
        queryBuilder.append(" '' as fd,");
        queryBuilder.append(" '' as gr,");
        queryBuilder.append(" '' as frtref,");
        queryBuilder.append(" '' as shpref,");
        queryBuilder.append(" '' as conref,");
        queryBuilder.append(" date_format(now(),'%m/%d/%Y') as updatedDate,");
        queryBuilder.append(" cast(now() as time) as updatedTime,");
        queryBuilder.append(" gc.codedesc as senderMappingId");
        queryBuilder.append(" from ");
        queryBuilder.append(logiwareDb).append(".kn_bkg_envelope env");
        queryBuilder.append(" join ");
        queryBuilder.append(logiwareDb).append(".kn_bkg_details bkg");
        queryBuilder.append(" on env.id = bkg.envelope_id join ");
        queryBuilder.append(logiwareDb).append(".kn_sailing_details sail");
        queryBuilder.append(" on bkg.id = sail.bkg_id join ");
        queryBuilder.append(logiwareDb).append(".kn_cargo_details cargo");
        queryBuilder.append(" on bkg.id = cargo.bkg_id join ");
        queryBuilder.append(bluescreenDb).append(".sched dest");
        queryBuilder.append(" on bkg.cfs_destination = dest.unctcd join ");
        queryBuilder.append(bluescreenDb).append(".ports dest_port");
        queryBuilder.append(" on dest.schnum = dest_port.schedk and dest_port.prtsc = 'Y' left join ");
        queryBuilder.append(logiwareDb).append(".genericcode_dup gc");
        queryBuilder.append(" on bkg.customer_control_code = gc.code join ");
        queryBuilder.append(logiwareDb).append(".codetype ct");
        queryBuilder.append(" on ct.description = '").append(senderMappingDesc).append("' left join ");
        queryBuilder.append(bluescreenDb).append(".frtfwd ff");
        queryBuilder.append(" on gc.codedesc = ff.actnum left join ");
        queryBuilder.append(bluescreenDb).append(".consig con");
        queryBuilder.append(" on gc.codedesc = con.connum left join ");
        queryBuilder.append(logiwareDb).append(".kn_haz_details haz");
        queryBuilder.append(" on cargo.id = haz.cargo_id left join ");
        queryBuilder.append(logiwareDb).append(".kn_pickup_details pickup");
        queryBuilder.append(" on bkg.id = pickup.bkg_id left join ");
        queryBuilder.append(bluescreenDb).append(".sched org");
        queryBuilder.append(" on bkg.cfs_origin = org.unctcd left join ");
        queryBuilder.append(bluescreenDb).append(".loctn orgl");
        queryBuilder.append(" on org.schnum = orgl.sched");
        queryBuilder.append(" where bkg.id in(").append(valueMap.get("bookingIds")).append(")");
        queryBuilder.append(" group by bkg.id");
        return queryBuilder;
    }

    public static StringBuilder fetchBookingHaz(Map<String, String> valueMap) {
        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("select");
        queryBuilder.append(" haz.un_number as unNumber,");
        queryBuilder.append(" haz.shipping_name as properShippingName,");
        queryBuilder.append(" haz.class as hazClass,");
        queryBuilder.append(" haz.flash_point as flashPoint,");
        queryBuilder.append(" haz.flash_point_flag as flashPointFlag,");
        queryBuilder.append(" haz.pack_group as packageGroup");
        queryBuilder.append(" from ");
        queryBuilder.append(logiwareDb).append(".kn_bkg_details bkg");
        queryBuilder.append(" join ").append(logiwareDb).append(".kn_cargo_details cargo");
        queryBuilder.append(" on bkg.id = cargo.bkg_id ");
        queryBuilder.append(" join ").append(logiwareDb).append(".kn_haz_details haz ");
        queryBuilder.append(" on cargo.id = haz.cargo_id ");
        queryBuilder.append(" where bkg.id in (").append(valueMap.get("bookingIds")).append(")");
        return queryBuilder;
    }
}
