package com.logiware.excel;

import java.io.OutputStream;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFColor;
import org.apache.poi.xssf.usermodel.XSSFFont;

/**
 *
 * @author Lakshmi Naryanan
 */
public class IBaseExcelCreator {

    protected String fileName;
    protected String sheetName;
    protected OutputStream outputStream;
    protected SXSSFWorkbook workbook;
    protected CreationHelper helper;
    protected Sheet sheet;
    protected Row row;
    protected Cell cell;
    protected Integer rowIndex = -1;
    protected Integer columnIndex = -1;
    protected XSSFColor BLACK;
    protected XSSFColor RED;
    protected XSSFColor WHITE;
    protected XSSFColor BG_BLACK;
    protected XSSFColor BG_WHITE;
    protected XSSFColor DARK_BLUE;
    protected XSSFColor LIGHT_BLUE;
    protected XSSFColor ORANGE_RED;
    protected XSSFColor LIGHT_ORANGE;
    protected XSSFColor SKY_BLUE;
    protected XSSFColor DARK_ASH;
    protected XSSFColor LIGHT_ASH;
    protected XSSFColor LIGHT_GRAY;
    protected XSSFColor LAVENDAR;
    protected XSSFColor LIGHT_GREEN;
    protected XSSFColor LIGHTER_GRAY;
    protected XSSFColor BG_YELLOW;
    protected XSSFFont blackBoldFont16;
    protected XSSFFont blackBoldFont15;
    protected XSSFFont blackBoldFont12;
    protected XSSFFont blackNormalFont12;
    protected XSSFFont blackBoldFont10;
    protected XSSFFont blackBoldFont11;
    protected XSSFFont redBoldFont10;
    protected XSSFFont blackNormalFont10;
    protected XSSFFont redNormalFont10;
    protected XSSFFont blackNormalFont11;
    protected XSSFFont whiteNormalFont11;
    protected CellStyle baseHeaderCellStyleLeftBold;
    protected CellStyle baseHeaderCellStyleCenterBold;
    protected CellStyle baseHeaderCellStyleRightBold;
    protected CellStyle secondaryHeaderCellStyleLeftNormal;
    protected CellStyle secondaryHeaderCellStyleCenterNormal;
    protected CellStyle secondaryHeaderCellStyleRightNormal;
    protected CellStyle lightGrayHeaderCellStyleLeftBold;
    protected CellStyle lightGrayHeaderCellStyleCenterBold;
    protected CellStyle lightGrayHeaderCellStyleRightBold;
    protected CellStyle headerCellStyleLeftBold;
    protected CellStyle headerCellStyleCenterBold;
    protected CellStyle headerCellStyleRightBold;
    protected CellStyle subHeaderOneCellStyleLeftBold;
    protected CellStyle subHeaderOneCellStyleLeftNormal;
    protected CellStyle subHeaderOneCellStyleCenterBold;
    protected CellStyle subHeaderOneCellStyleCenterNormal;
    protected CellStyle subHeaderOneCellStyleRightBold;
    protected CellStyle subHeaderOneCellStyleRightNormal;
    protected CellStyle subHeaderTwoCellStyleLeftBold;
    protected CellStyle subHeaderTwoCellStyleLeftNormal;
    protected CellStyle subHeaderTwoCellStyleCenterBold;
    protected CellStyle subHeaderTwoCellStyleCenterNormal;
    protected CellStyle subHeaderTwoCellStyleRightBold;
    protected CellStyle subHeaderTwoCellStyleRightNormal;
    protected CellStyle subHeaderOneCellStyleGreen;
    protected CellStyle subHeaderOneCellStyleGray;
    protected CellStyle tableHeaderCellStyleLeftBold;
    protected CellStyle tableHeaderCellStyleCenterBold;
    protected CellStyle tableHeaderCellStyleRightBold;
    protected CellStyle tableOddRowCellStyleLeftBold;
    protected CellStyle tableOddRowCellStyleLeftNormal;
    protected CellStyle tableOddRowCellStyleCenterBold;
    protected CellStyle tableOddRowCellStyleCenterNormal;
    protected CellStyle tableOddRowCellStyleRightBold;
    protected CellStyle tableOddRowCellStyleRightNormal;
    protected CellStyle tableEvenRowCellStyleLeftBold;
    protected CellStyle tableEvenRowCellStyleLeftNormal;
    protected CellStyle tableEvenRowCellStyleCenterBold;
    protected CellStyle tableEvenRowCellStyleCenterNormal;
    protected CellStyle tableEvenRowCellStyleRightBold;
    protected CellStyle tableEvenRowCellStyleRightNormal;
    protected CellStyle lightAshCellStyleLeftBold;
    protected CellStyle lightAshCellStyleLeftNormal;
    protected CellStyle lightAshCellStyleCenterBold;
    protected CellStyle lightAshCellStyleCenterNormal;
    protected CellStyle lightAshCellStyleRightBold;
    protected CellStyle lightAshCellStyleRightNormal;
    protected CellStyle darkAshCellStyleLeftBold;
    protected CellStyle darkAshCellStyleLeftNormal;
    protected CellStyle darkAshCellStyleCenterBold;
    protected CellStyle darkAshCellStyleCenterNormal;
    protected CellStyle darkAshCellStyleRightBold;
    protected CellStyle darkAshCellStyleRightNormal;
    protected CellStyle lavendarCellStyleLeftBold;
    protected CellStyle lavendarCellStyleLeftNormal;
    protected CellStyle lavendarCellStyleCenterBold;
    protected CellStyle lavendarCellStyleCenterNormal;
    protected CellStyle lavendarCellStyleRightBold;
    protected CellStyle lavendarCellStyleRightNormal;
    protected CellStyle cellStyleLeftBold;
    protected CellStyle cellStyleLeftNormal;
    protected CellStyle cellStyleCenterBold;
    protected CellStyle cellStyleCenterNormal;
    protected CellStyle cellStyleRightBold;
    protected CellStyle cellStyleRightNormal;
    protected CellStyle redCellStyleLeftBold;
    protected CellStyle redCellStyleLeftNormal;
    protected CellStyle redCellStyleCenterBold;
    protected CellStyle redCellStyleCenterNormal;
    protected CellStyle redCellStyleRightBold;
    protected CellStyle redCellStyleRightNormal;
    protected CellStyle cellStyleLeftNormalForTruker;
    protected CellStyle cellStyleCenterNormalForTruker;
    protected CellStyle lclCellStyleLeftNormal;
    protected CellStyle lclCellStyleLeftNormalArial10;
    protected CellStyle redLclCellStyleRightNormalArial10;
    protected CellStyle lclCellStyleLeftBoldArial15;
    protected CellStyle lclCellStyleLeftBoldArial12;
    protected CellStyle lclCellStyleLeftBoldArial11;
    protected CellStyle lclCellStyleLeftBoldArial10;
    protected CellStyle lclCellStyleBoldArialBorder;
    protected CellStyle lclCellStyleBoldArialLine;
    protected CellStyle lclCellStyleBoldArialBottomLine;
    protected CellStyle lclCellStyleBoldArialBottomRightLine;
    protected CellStyle lclCellStyleNormalArial10;
    protected CellStyle cellStyleRightNormalArial10;
    protected CellStyle cellStyleRightBoldArial10;
    protected CellStyle blackCellBackground;
    protected CellStyle subHeaderTwoCellStyleCenter10;
    protected CellStyle subHeaderOneCellStyleCenter10;
    protected CellStyle subHeaderTwoCellStyleLeft10;
    protected CellStyle cellStyleCenterBoldYellow;
    protected short integerDataFormat;
    protected short doubleDataFormat;
}
